import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFile, mkdir, writeFile, access } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";

const builtins = [...builtinModules, ...builtinModules.map(m => `node:${m}`)];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

// ── Deploy to the development vault ──────────────────────────────────────────
//
// Copy rather than symlink: this repo lives in iCloud Drive, and pointing a
// vault at an iCloud path risks Obsidian stalling on a file iCloud has evicted.
// A copy is a few milliseconds and leaves the vault self-contained.
//
// Override the destination with VAULT_PLUGIN_DIR, or set it empty to skip.
const PLUGIN_ID = JSON.parse(
  await import("node:fs").then(fs => fs.promises.readFile("manifest.json", "utf8")),
).id;

// Where to deploy is a property of this machine, not of the plugin, so it is
// read from the environment or from a gitignored file rather than baked in.
// `.dev-vault` lists vaults one per line, so a test vault and the one the
// plugin is used in stay in step. Without either, the build doesn't deploy.
function devVaults() {
  if (process.env.VAULT_PLUGIN_DIR !== undefined) {
    return process.env.VAULT_PLUGIN_DIR ? [process.env.VAULT_PLUGIN_DIR] : [];
  }
  try {
    return readFileSync(".dev-vault", "utf8")
      .split("\n")
      .map(line => line.trim())
      .filter(Boolean)
      .map(vault => join(vault, ".obsidian/plugins", PLUGIN_ID));
  } catch {
    return [];   // no local config: nothing to deploy to
  }
}
const vaultDirs = devVaults();

const ASSETS = ["main.js", "manifest.json", "styles.css"];

async function exists(p) {
  try { await access(p); return true; } catch { return false; }
}

async function deploy() {
  for (const vaultDir of vaultDirs) await deployTo(vaultDir);
}

async function deployTo(vaultDir) {
  // Only deploy into a real vault — keeps CI (and any other machine) quiet
  // instead of creating a stray directory tree.
  if (!(await exists(dirname(dirname(vaultDir))))) {
    console.log(`  (no vault at ${vaultDir}, skipping deploy)`);
    return;
  }
  await mkdir(vaultDir, { recursive: true });
  for (const asset of ASSETS) {
    if (await exists(asset)) await copyFile(asset, join(vaultDir, asset));
  }
  // Marker for pjeby/hot-reload: with that plugin installed, Obsidian reloads
  // this plugin whenever main.js changes. Inert if it isn't installed.
  await writeFile(join(vaultDir, ".hotreload"), "");
  console.log(`  deployed → ${vaultDir}`);
}

/** Redeploy after every successful build, including watch-mode rebuilds. */
const deployPlugin = {
  name: "deploy-to-vault",
  setup(build) {
    build.onEnd(async result => {
      if (result.errors.length > 0) return;
      await deploy();
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  // The debug bridge (src/debugBridge.ts) exists only in a debug build.
  define: { ATTENTION_DEBUG: process.env.ATTENTION_DEBUG === "1" ? "true" : "false" },
  outfile: "main.js",
  plugins: [deployPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  // styles.css isn't an esbuild input, so watch it separately — editing CSS
  // should land in the vault without touching a .ts file to force a rebuild.
  const { watch } = await import("node:fs");
  watch("styles.css", () => { void deploy(); });
  await context.watch();
}
