/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AttentionPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  colors: ["#f5c542", "#7ec96b", "#63b3ed", "#e879a6", "#b794f4"],
  defaultColor: "#f5c542",
  enableMarkdownHost: true,
  enableTranscriptHost: true,
  trackReplays: false,
  resurfaceCount: 10,
  keepOrphanedSidecars: true
};
var AttentionSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Where to annotate").setHeading();
    new import_obsidian.Setting(containerEl).setName("Markdown notes").setDesc("Highlight and comment inside notes. The note itself is never modified.").addToggle(
      (t) => t.setValue(this.plugin.settings.enableMarkdownHost).onChange(async (v) => {
        this.plugin.settings.enableMarkdownHost = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Transcripts").setDesc(
      "Highlight and comment on transcript lines in the Media Transcript plugin. Has no effect if that plugin is not installed."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.enableTranscriptHost).onChange(async (v) => {
        this.plugin.settings.enableTranscriptHost = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Review").setHeading();
    new import_obsidian.Setting(containerEl).setName("Resurface count").setDesc("How many annotations to bring back at a time, preferring ones you have not revisited.").addSlider(
      (s) => s.setLimits(3, 50, 1).setValue(this.plugin.settings.resurfaceCount).onChange(async (v) => {
        this.plugin.settings.resurfaceCount = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Advanced").setHeading();
    new import_obsidian.Setting(containerEl).setName("Count replays").setDesc(
      "Record how often you replay a transcript segment. A weaker signal than a highlight, but a much denser one \u2014 useful for spotting what actually held your attention."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.trackReplays).onChange(async (v) => {
        this.plugin.settings.trackReplays = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Keep annotations when a file is deleted").setDesc("Leaves the .anno.json behind so annotations survive an accidental delete.").addToggle(
      (t) => t.setValue(this.plugin.settings.keepOrphanedSidecars).onChange(async (v) => {
        this.plugin.settings.keepOrphanedSidecars = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Rebuild index").setDesc("Rescan every sidecar in the vault. Safe to run any time \u2014 the index is derived data.").addButton(
      (b) => b.setButtonText("Rebuild").onClick(async () => {
        await this.plugin.rebuildIndex();
      })
    );
  }
};

// src/store/paths.ts
var SIDECAR_SUFFIX = ".anno.json";
function sidecarPathFor(targetPath) {
  return targetPath + SIDECAR_SUFFIX;
}
function isSidecarPath(path) {
  return path.endsWith(SIDECAR_SUFFIX);
}
function targetPathFor(sidecarPath) {
  if (!isSidecarPath(sidecarPath))
    return null;
  const target = sidecarPath.slice(0, -SIDECAR_SUFFIX.length);
  if (target.length === 0 || isSidecarPath(target))
    return null;
  return target;
}

// src/store/sidecar.ts
var import_obsidian2 = require("obsidian");

// src/model.ts
function emptyFile(target) {
  return { version: 1, target, annotations: [] };
}
function newId() {
  return Math.random().toString(36).slice(2, 10);
}
function isComment(a) {
  return a.body !== null && a.body.trim().length > 0;
}

// src/store/sidecar.ts
async function loadSidecar(app, targetPath) {
  const file = app.vault.getAbstractFileByPath(sidecarPathFor(targetPath));
  if (!(file instanceof import_obsidian2.TFile))
    return emptyFile(targetPath);
  try {
    const parsed = JSON.parse(await app.vault.read(file));
    if (parsed && typeof parsed === "object" && Array.isArray(parsed.annotations)) {
      return { ...parsed, target: targetPath };
    }
  } catch (e) {
  }
  return emptyFile(targetPath);
}
async function saveSidecar(app, data) {
  const path = sidecarPathFor(data.target);
  const existing = app.vault.getAbstractFileByPath(path);
  if (data.annotations.length === 0) {
    if (existing instanceof import_obsidian2.TFile)
      await app.fileManager.trashFile(existing);
    return;
  }
  const body = JSON.stringify(data, null, 2);
  if (existing instanceof import_obsidian2.TFile)
    await app.vault.modify(existing, body);
  else
    await app.vault.create(path, body);
}

// src/store/review.ts
var BUCKET_ORDER = ["today", "week", "month", "older"];
var DAY = 864e5;
function bucketize(entries, now) {
  const out = { today: [], week: [], month: [], older: [] };
  for (const e of entries) {
    const age = now - Date.parse(e.annotation.created);
    if (age < DAY)
      out.today.push(e);
    else if (age < 7 * DAY)
      out.week.push(e);
    else if (age < 30 * DAY)
      out.month.push(e);
    else
      out.older.push(e);
  }
  return out;
}
function pickResurface(entries, n, rand) {
  const decorated = entries.map((entry) => ({ entry, jitter: rand() }));
  decorated.sort((a, b) => {
    const seen = a.entry.annotation.reviewed.length - b.entry.annotation.reviewed.length;
    if (seen !== 0)
      return seen;
    return a.jitter - b.jitter;
  });
  return decorated.slice(0, Math.max(0, n)).map((d) => d.entry);
}
function byNewest(a, b) {
  return b.annotation.created.localeCompare(a.annotation.created);
}

// src/store/attentionIndex.ts
var AttentionIndex = class {
  constructor(app) {
    this.app = app;
    this.entries = [];
  }
  /** Rescan every sidecar in the vault. Cheap enough to run on load. */
  async rebuild() {
    const next = [];
    for (const file of this.app.vault.getFiles()) {
      if (!isSidecarPath(file.path))
        continue;
      const targetPath = targetPathFor(file.path);
      if (!targetPath)
        continue;
      const data = await loadSidecar(this.app, targetPath);
      for (const annotation of data.annotations) {
        next.push({ targetPath, annotation });
      }
    }
    next.sort(byNewest);
    this.entries = next;
  }
  /** Replace one file's entries in place (after an edit, without a full scan). */
  replaceFile(targetPath, annotations) {
    this.entries = this.entries.filter((e) => e.targetPath !== targetPath);
    for (const annotation of annotations)
      this.entries.push({ targetPath, annotation });
    this.entries.sort(byNewest);
  }
  /** Follow a rename so the index doesn't point at a path that's gone. */
  renameFile(oldPath, newPath) {
    for (const e of this.entries) {
      if (e.targetPath === oldPath)
        e.targetPath = newPath;
    }
  }
  all() {
    return this.entries;
  }
  buckets(now = Date.now()) {
    return bucketize(this.entries, now);
  }
  resurface(n, rand) {
    return pickResurface(this.entries, n, rand);
  }
};

// src/views/ReviewView.ts
var import_obsidian3 = require("obsidian");
var VIEW_TYPE_REVIEW = "attention-review";
var BUCKET_LABELS = {
  today: "Today",
  week: "This week",
  month: "This month",
  older: "Earlier"
};
var ReviewView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_REVIEW;
  }
  getDisplayText() {
    return "Attention";
  }
  getIcon() {
    return "highlighter";
  }
  async onOpen() {
    this.render();
  }
  render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("at-review");
    const buckets = this.plugin.index.buckets();
    const total = this.plugin.index.all().length;
    const header = root.createDiv("at-review-header");
    header.createSpan({ text: `${total} marked`, cls: "at-review-total" });
    const resurface = header.createEl("button", { text: "Resurface", cls: "at-btn" });
    resurface.addEventListener("click", () => this.renderResurfaced());
    if (total === 0) {
      root.createDiv("at-empty").setText(
        "Nothing marked yet. Select text in a note to highlight it or leave a comment."
      );
      return;
    }
    for (const key of BUCKET_ORDER) {
      const entries = buckets[key];
      if (entries.length === 0)
        continue;
      root.createDiv("at-bucket-title").setText(`${BUCKET_LABELS[key]} \xB7 ${entries.length}`);
      for (const entry of entries)
        this.renderEntry(root, entry);
    }
  }
  renderResurfaced() {
    const n = this.plugin.settings.resurfaceCount;
    const picked = this.plugin.index.resurface(n, () => Math.random());
    const root = this.contentEl;
    root.empty();
    root.addClass("at-review");
    const header = root.createDiv("at-review-header");
    header.createSpan({ text: `${picked.length} resurfaced`, cls: "at-review-total" });
    const back = header.createEl("button", { text: "All", cls: "at-btn" });
    back.addEventListener("click", () => this.render());
    for (const entry of picked)
      this.renderEntry(root, entry);
  }
  renderEntry(root, entry) {
    var _a, _b;
    const { annotation, targetPath } = entry;
    const el = root.createDiv("at-entry");
    el.setCssProps({ "--at-color": annotation.color });
    el.createDiv("at-quote").setText(annotation.anchor.quote);
    if (isComment(annotation)) {
      el.createDiv("at-body").setText((_a = annotation.body) != null ? _a : "");
    }
    const meta = el.createDiv("at-meta");
    meta.createSpan({ text: (_b = targetPath.split("/").pop()) != null ? _b : targetPath, cls: "at-source" });
    if (annotation.anchor.kind === "transcript") {
      meta.createSpan({ text: fmtTime(annotation.anchor.start), cls: "at-time" });
    }
    el.addEventListener("click", () => {
      void this.open(entry);
    });
  }
  async open(entry) {
    const file = this.app.vault.getAbstractFileByPath(entry.targetPath);
    if (!(file instanceof import_obsidian3.TFile))
      return;
    await this.app.workspace.getLeaf(false).openFile(file);
    await this.plugin.markReviewed(entry);
  }
};
function fmtTime(seconds) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

// src/store/annotationStore.ts
var AnnotationStore = class {
  constructor(app, index) {
    this.app = app;
    this.index = index;
    this.cache = /* @__PURE__ */ new Map();
    this.listeners = [];
  }
  /** Annotations for a file, from cache when we have it. */
  async get(targetPath) {
    const cached = this.cache.get(targetPath);
    if (cached)
      return cached;
    const loaded = await loadSidecar(this.app, targetPath);
    this.cache.set(targetPath, loaded);
    return loaded;
  }
  /** Synchronous peek for render paths that can't await. Empty if not loaded. */
  peek(targetPath) {
    var _a, _b;
    return (_b = (_a = this.cache.get(targetPath)) == null ? void 0 : _a.annotations) != null ? _b : [];
  }
  /** Load into the cache so a later peek() has something to paint. */
  async warm(targetPath) {
    await this.get(targetPath);
    this.emit(targetPath);
  }
  async add(targetPath, annotation) {
    const data = await this.get(targetPath);
    data.annotations.push(annotation);
    await this.commit(targetPath, data);
  }
  async update(targetPath, id, patch) {
    const data = await this.get(targetPath);
    const target = data.annotations.find((a) => a.id === id);
    if (!target)
      return;
    Object.assign(target, patch, { updated: new Date().toISOString() });
    await this.commit(targetPath, data);
  }
  async remove(targetPath, id) {
    const data = await this.get(targetPath);
    const before = data.annotations.length;
    data.annotations = data.annotations.filter((a) => a.id !== id);
    if (data.annotations.length === before)
      return;
    await this.commit(targetPath, data);
  }
  /** Drop a cache entry (after an external edit or a rename). */
  forget(targetPath) {
    this.cache.delete(targetPath);
  }
  async commit(targetPath, data) {
    await saveSidecar(this.app, data);
    this.cache.set(targetPath, data);
    this.index.replaceFile(targetPath, data.annotations);
    this.emit(targetPath);
  }
  onChange(listener) {
    this.listeners.push(listener);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== listener);
    };
  }
  emit(targetPath) {
    for (const l of this.listeners)
      l(targetPath);
  }
};

// src/hosts/markdown/MarkdownHost.ts
var import_obsidian5 = require("obsidian");

// src/anchor/textQuote.ts
var CONTEXT_LEN = 32;
function describe(text, from, to) {
  return {
    quote: text.slice(from, to),
    prefix: text.slice(Math.max(0, from - CONTEXT_LEN), from),
    suffix: text.slice(to, to + CONTEXT_LEN),
    from,
    to
  };
}
function commonSuffixLen(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[a.length - 1 - n] === b[b.length - 1 - n])
    n++;
  return n;
}
function commonPrefixLen(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[n] === b[n])
    n++;
  return n;
}
function allOccurrences(text, needle) {
  if (needle.length === 0)
    return [];
  const out = [];
  let at = text.indexOf(needle);
  while (at >= 0) {
    out.push(at);
    at = text.indexOf(needle, at + 1);
  }
  return out;
}
function resolve(text, anchor) {
  const { quote } = anchor;
  if (quote.length === 0)
    return null;
  if (text.slice(anchor.from, anchor.to) === quote) {
    return { from: anchor.from, to: anchor.to, how: "exact" };
  }
  const hits = allOccurrences(text, quote);
  if (hits.length === 0)
    return null;
  if (hits.length === 1) {
    return { from: hits[0], to: hits[0] + quote.length, how: "unique" };
  }
  let best = -1;
  let bestScore = -1;
  for (const at of hits) {
    const score = commonSuffixLen(text.slice(0, at), anchor.prefix) + commonPrefixLen(text.slice(at + quote.length), anchor.suffix);
    if (score > bestScore) {
      bestScore = score;
      best = at;
    }
  }
  if (bestScore > 0) {
    return { from: best, to: best + quote.length, how: "context" };
  }
  let nearest = hits[0];
  for (const at of hits) {
    if (Math.abs(at - anchor.from) < Math.abs(nearest - anchor.from))
      nearest = at;
  }
  return { from: nearest, to: nearest + quote.length, how: "nearest" };
}
function nthOccurrence(text, needle, n) {
  if (needle.length === 0 || n < 0)
    return -1;
  let at = text.indexOf(needle);
  for (let i = 0; i < n && at >= 0; i++)
    at = text.indexOf(needle, at + 1);
  return at;
}
function countOccurrences(before, needle) {
  if (needle.length === 0)
    return 0;
  let n = 0;
  let at = before.indexOf(needle);
  while (at >= 0) {
    n++;
    at = before.indexOf(needle, at + 1);
  }
  return n;
}

// src/ui/SelectionPopover.ts
var SelectionPopover = class {
  constructor(colors) {
    this.colors = colors;
    this.el = null;
    this.dismiss = () => this.hide();
  }
  showAt(rect, actions) {
    this.hide();
    const el = document.createElement("div");
    el.className = "at-popover";
    for (const color of this.colors) {
      const swatch = el.createEl("button", { cls: "at-swatch" });
      swatch.style.background = color;
      swatch.setAttribute("aria-label", `Highlight ${color}`);
      swatch.addEventListener("mousedown", (e) => {
        e.preventDefault();
        actions.onHighlight(color);
        this.hide();
      });
    }
    const comment = el.createEl("button", { cls: "at-pop-btn", text: "\u{1F4AC}" });
    comment.setAttribute("aria-label", "Add a comment");
    comment.addEventListener("mousedown", (e) => {
      e.preventDefault();
      actions.onComment();
      this.hide();
    });
    if (actions.onRemove) {
      const remove = el.createEl("button", { cls: "at-pop-btn", text: "\u2715" });
      remove.setAttribute("aria-label", "Remove highlight");
      remove.addEventListener("mousedown", (e) => {
        var _a;
        e.preventDefault();
        (_a = actions.onRemove) == null ? void 0 : _a.call(actions);
        this.hide();
      });
    }
    document.body.appendChild(el);
    this.el = el;
    const { width, height } = el.getBoundingClientRect();
    const left = Math.min(
      Math.max(8, rect.left + rect.width / 2 - width / 2),
      window.innerWidth - width - 8
    );
    const above = rect.top - height - 8;
    el.style.left = `${left}px`;
    el.style.top = `${above < 8 ? rect.bottom + 8 : above}px`;
    window.setTimeout(() => {
      document.addEventListener("mousedown", this.dismiss);
      document.addEventListener("keydown", this.dismiss);
    }, 0);
  }
  hide() {
    var _a;
    document.removeEventListener("mousedown", this.dismiss);
    document.removeEventListener("keydown", this.dismiss);
    (_a = this.el) == null ? void 0 : _a.remove();
    this.el = null;
  }
};

// src/ui/CommentModal.ts
var import_obsidian4 = require("obsidian");
var CommentModal = class extends import_obsidian4.Modal {
  constructor(app, quote, initial, onSubmit) {
    super(app);
    this.quote = quote;
    this.onSubmit = onSubmit;
    this.value = initial;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("at-comment-modal");
    contentEl.createDiv("at-comment-quote").setText(this.quote);
    const input = contentEl.createEl("textarea", { cls: "at-comment-input" });
    input.value = this.value;
    input.placeholder = "What caught your attention?";
    input.addEventListener("input", () => {
      this.value = input.value;
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        this.submit();
      }
    });
    new import_obsidian4.Setting(contentEl).addButton(
      (b) => b.setButtonText("Save").setCta().onClick(() => this.submit())
    );
    window.setTimeout(() => input.focus(), 0);
  }
  submit() {
    this.onSubmit(this.value.trim());
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/hosts/markdown/MarkdownHost.ts
var MarkdownHost = class {
  constructor(app, plugin, store, settings) {
    this.app = app;
    this.plugin = plugin;
    this.store = store;
    this.settings = settings;
    /** The element right-clicked, captured before any menu is built. */
    this.lastTarget = null;
    this.popover = new SelectionPopover(settings.colors);
  }
  register() {
    this.plugin.registerDomEvent(
      document,
      "contextmenu",
      (e) => {
        this.lastTarget = e.target instanceof HTMLElement ? e.target : null;
      },
      true
    );
    this.plugin.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, info) => {
        this.onEditorMenu(menu, editor, info);
      })
    );
    this.plugin.registerDomEvent(document, "contextmenu", (e) => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
      if (!(view == null ? void 0 : view.file) || view.getMode() !== "preview")
        return;
      if (!this.hasSomethingToOffer(view))
        return;
      e.preventDefault();
      void this.showReadingMenu(e, view);
    });
  }
  detach() {
    this.popover.hide();
  }
  hasSomethingToOffer(view) {
    var _a, _b, _c;
    if ((_a = this.lastTarget) == null ? void 0 : _a.closest(".at-hl"))
      return true;
    const selection = window.getSelection();
    return ((_b = selection == null ? void 0 : selection.toString().trim().length) != null ? _b : 0) > 0 && view.contentEl.contains((_c = selection == null ? void 0 : selection.anchorNode) != null ? _c : null);
  }
  // ── Editing modes ──────────────────────────────────────────────────────────
  onEditorMenu(menu, editor, info) {
    var _a;
    const file = info.file;
    if (!file)
      return;
    const existing = (_a = this.lastTarget) == null ? void 0 : _a.closest(".at-hl");
    if (existing instanceof HTMLElement) {
      this.addExistingItems(menu, file, existing);
      return;
    }
    const from = editor.posToOffset(editor.getCursor("from"));
    const to = editor.posToOffset(editor.getCursor("to"));
    if (from === to)
      return;
    const anchor = {
      kind: "markdown",
      ...describe(editor.getValue(), from, to)
    };
    this.addCreateItems(menu, file, anchor);
  }
  // ── Reading mode ───────────────────────────────────────────────────────────
  async showReadingMenu(e, view) {
    var _a;
    const file = view.file;
    if (!file)
      return;
    const menu = new import_obsidian5.Menu();
    const existing = (_a = this.lastTarget) == null ? void 0 : _a.closest(".at-hl");
    if (existing instanceof HTMLElement) {
      this.addExistingItems(menu, file, existing);
    } else {
      const anchor = await this.captureRendered(view, file);
      if (!anchor)
        return;
      this.addCreateItems(menu, file, anchor);
    }
    menu.showAtMouseEvent(e);
  }
  /** Locate a reading-mode selection in the source by ordinal. */
  async captureRendered(view, file) {
    var _a;
    const selection = window.getSelection();
    const selected = (_a = selection == null ? void 0 : selection.toString()) != null ? _a : "";
    if (!selection || selected.trim().length === 0)
      return null;
    const source = await this.app.vault.cachedRead(file);
    const at = nthOccurrence(source, selected, this.renderedOrdinal(view, selection, selected));
    if (at < 0) {
      new import_obsidian5.Notice("Attention: cannot anchor a selection that crosses formatting.");
      return null;
    }
    return { kind: "markdown", ...describe(source, at, at + selected.length) };
  }
  /** How many identical strings precede this selection on screen. */
  renderedOrdinal(view, selection, selected) {
    const sel = selection.getRangeAt(0);
    const before = sel.cloneRange();
    before.selectNodeContents(view.contentEl);
    before.setEnd(sel.startContainer, sel.startOffset);
    return countOccurrences(before.toString(), selected);
  }
  // ── Menu items ─────────────────────────────────────────────────────────────
  addCreateItems(menu, file, anchor) {
    menu.addItem(
      (item) => item.setTitle("Highlight").setIcon("highlighter").setSection("attention").onClick(() => {
        void this.create(file, anchor, this.settings.defaultColor, null);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Highlight in colour\u2026").setIcon("palette").setSection("attention").onClick((e) => {
        this.popover.showAt(rectOf(e), {
          onHighlight: (color) => {
            void this.create(file, anchor, color, null);
          },
          onComment: () => this.promptComment(file, anchor, "")
        });
      })
    );
    menu.addItem(
      (item) => item.setTitle("Comment\u2026").setIcon("message-square").setSection("attention").onClick(() => this.promptComment(file, anchor, ""))
    );
  }
  addExistingItems(menu, file, el) {
    const id = el.dataset.atId;
    if (!id)
      return;
    menu.addItem(
      (item) => item.setTitle("Edit comment\u2026").setIcon("message-square").setSection("attention").onClick(() => {
        void this.editComment(file, id);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Change colour\u2026").setIcon("palette").setSection("attention").onClick(() => {
        this.popover.showAt(el.getBoundingClientRect(), {
          onHighlight: (color) => {
            void this.store.update(file.path, id, { color });
          },
          onComment: () => {
            void this.editComment(file, id);
          }
        });
      })
    );
    menu.addItem(
      (item) => item.setTitle("Remove highlight").setIcon("trash").setSection("attention").setWarning(true).onClick(() => {
        void this.store.remove(file.path, id);
      })
    );
  }
  // ── Actions ────────────────────────────────────────────────────────────────
  promptComment(file, anchor, initial) {
    new CommentModal(this.app, anchor.quote, initial, (body) => {
      void this.create(file, anchor, this.settings.defaultColor, body || null);
    }).open();
  }
  async editComment(file, id) {
    var _a;
    const data = await this.store.get(file.path);
    const annotation = data.annotations.find((a) => a.id === id);
    if (!annotation)
      return;
    new CommentModal(this.app, annotation.anchor.quote, (_a = annotation.body) != null ? _a : "", (body) => {
      void this.store.update(file.path, id, { body: body || null });
    }).open();
  }
  async create(file, anchor, color, body) {
    const annotation = {
      id: newId(),
      anchor,
      color,
      body,
      created: new Date().toISOString(),
      reviewed: []
    };
    await this.store.add(file.path, annotation);
  }
};
function rectOf(e) {
  const x = e instanceof MouseEvent ? e.clientX : window.innerWidth / 2;
  const y = e instanceof MouseEvent ? e.clientY : window.innerHeight / 2;
  return new DOMRect(x, y, 0, 0);
}

// src/hosts/markdown/decorations.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_obsidian6 = require("obsidian");
var refreshAnnotations = import_state.StateEffect.define();
function build(view, provider) {
  var _a, _b;
  const path = (_b = (_a = view.state.field(import_obsidian6.editorInfoField, false)) == null ? void 0 : _a.file) == null ? void 0 : _b.path;
  if (!path)
    return import_view.Decoration.none;
  const annotations = provider(path);
  if (annotations.length === 0)
    return import_view.Decoration.none;
  const doc = view.state.doc.toString();
  const ranges = [];
  for (const a of annotations) {
    if (a.anchor.kind !== "markdown")
      continue;
    const at = resolve(doc, a.anchor);
    if (!at || at.from === at.to)
      continue;
    ranges.push(
      import_view.Decoration.mark({
        class: isComment(a) ? "at-hl at-hl-comment" : "at-hl",
        attributes: { style: `--at-color: ${a.color}`, "data-at-id": a.id }
      }).range(at.from, at.to)
    );
  }
  return import_view.Decoration.set(ranges, true);
}
function annotationDecorations(provider) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = build(view, provider);
      }
      update(u) {
        const refreshed = u.transactions.some(
          (t) => t.effects.some((e) => e.is(refreshAnnotations))
        );
        if (u.docChanged || u.viewportChanged || refreshed) {
          this.decorations = build(u.view, provider);
        }
      }
    },
    { decorations: (v) => v.decorations }
  );
}
function repaintEditors(app) {
  app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
    const view = leaf.view;
    if (!(view instanceof import_obsidian6.MarkdownView))
      return;
    const cm = view.editor.cm;
    cm == null ? void 0 : cm.dispatch({ effects: refreshAnnotations.of() });
  });
}

// src/hosts/markdown/readingMode.ts
function readingModeHighlighter(provider) {
  return (el, ctx) => {
    const annotations = provider(ctx.sourcePath);
    if (annotations.length === 0)
      return;
    for (const a of annotations) {
      if (a.anchor.kind !== "markdown")
        continue;
      paint(el, a);
    }
  };
}
function paint(root, a) {
  const needle = a.anchor.quote;
  if (!needle)
    return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const targets = [];
  for (let n = walker.nextNode(); n; n = walker.nextNode()) {
    const text = n;
    if (text.data.includes(needle) && !isInsideHighlight(text))
      targets.push(text);
  }
  for (const node of targets) {
    const at = node.data.indexOf(needle);
    if (at < 0)
      continue;
    const tail = node.splitText(at);
    tail.splitText(needle.length);
    const span = document.createElement("span");
    span.className = isComment(a) ? "at-hl at-hl-comment" : "at-hl";
    span.style.setProperty("--at-color", a.color);
    span.dataset.atId = a.id;
    tail.replaceWith(span);
    span.appendChild(tail);
  }
}
function isInsideHighlight(node) {
  var _a;
  return ((_a = node.parentElement) == null ? void 0 : _a.closest(".at-hl")) != null;
}

// src/main.ts
var AttentionPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.markdownHost = null;
  }
  async onload() {
    await this.loadSettings();
    this.index = new AttentionIndex(this.app);
    this.store = new AnnotationStore(this.app, this.index);
    this.registerView(VIEW_TYPE_REVIEW, (leaf) => new ReviewView(leaf, this));
    if (this.settings.enableMarkdownHost)
      this.setupMarkdownHost();
    this.register(this.store.onChange(() => {
      repaintEditors(this.app);
      this.rerenderReadingViews();
      this.refreshReviewViews();
    }));
    this.registerEvent(this.app.workspace.on("file-open", (file) => {
      if (file)
        void this.store.warm(file.path);
    }));
    this.app.workspace.onLayoutReady(() => {
      void this.rebuildIndex();
    });
    this.addRibbonIcon("highlighter", "Attention", () => {
      void this.openReview();
    });
    this.addCommand({
      id: "open-review",
      name: "Open attention review",
      callback: () => {
        void this.openReview();
      }
    });
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      void this.handleRename(file, oldPath);
    }));
    this.registerEvent(this.app.vault.on("delete", (file) => {
      void this.handleDelete(file);
    }));
    this.addSettingTab(new AttentionSettingTab(this.app, this));
  }
  setupMarkdownHost() {
    const provider = (path) => this.store.peek(path);
    this.registerEditorExtension(annotationDecorations(provider));
    this.registerMarkdownPostProcessor(readingModeHighlighter(provider));
    this.markdownHost = new MarkdownHost(this.app, this, this.store, this.settings);
    this.markdownHost.register();
  }
  /** Reading mode caches its HTML, so post-processors only re-run on request. */
  rerenderReadingViews() {
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const view = leaf.view;
      if (view instanceof import_obsidian7.MarkdownView && view.getMode() === "preview") {
        view.previewMode.rerender(true);
      }
    }
  }
  async rebuildIndex() {
    await this.index.rebuild();
    this.refreshReviewViews();
  }
  /** Record that an annotation resurfaced, so future picks can prefer others. */
  async markReviewed(entry) {
    const data = await loadSidecar(this.app, entry.targetPath);
    const target = data.annotations.find((a) => a.id === entry.annotation.id);
    if (!target)
      return;
    target.reviewed.push(new Date().toISOString());
    await saveSidecar(this.app, data);
    this.index.replaceFile(entry.targetPath, data.annotations);
  }
  async openReview() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_REVIEW);
    if (existing.length > 0) {
      await this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (!leaf)
      return;
    await leaf.setViewState({ type: VIEW_TYPE_REVIEW, active: true });
    await this.app.workspace.revealLeaf(leaf);
  }
  refreshReviewViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_REVIEW)) {
      if (leaf.view instanceof ReviewView)
        leaf.view.render();
    }
  }
  /**
   * Keep the sidecar beside its target. Folder moves need no work — the sidecar
   * is a sibling, so it travels with the folder — only a file's own rename does.
   */
  async handleRename(file, oldPath) {
    if (!(file instanceof import_obsidian7.TFile) || isSidecarPath(file.path))
      return;
    const old = this.app.vault.getAbstractFileByPath(sidecarPathFor(oldPath));
    if (!(old instanceof import_obsidian7.TFile))
      return;
    const nextPath = sidecarPathFor(file.path);
    if (old.path === nextPath)
      return;
    try {
      await this.app.fileManager.renameFile(old, nextPath);
      const data = await loadSidecar(this.app, file.path);
      await saveSidecar(this.app, data);
      this.store.forget(oldPath);
      this.index.renameFile(oldPath, file.path);
      this.refreshReviewViews();
    } catch (e) {
      new import_obsidian7.Notice(`Attention: could not move annotations for ${file.name}`);
      console.error(e);
    }
  }
  async handleDelete(file) {
    if (!(file instanceof import_obsidian7.TFile) || isSidecarPath(file.path))
      return;
    if (this.settings.keepOrphanedSidecars)
      return;
    const sidecar = this.app.vault.getAbstractFileByPath(sidecarPathFor(file.path));
    if (sidecar instanceof import_obsidian7.TFile)
      await this.app.fileManager.trashFile(sidecar);
    this.store.forget(file.path);
    this.index.replaceFile(file.path, []);
    this.refreshReviewViews();
  }
  onunload() {
    var _a;
    (_a = this.markdownHost) == null ? void 0 : _a.detach();
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved != null ? saved : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
