/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AttentionPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  colors: ["#f5c542", "#7ec96b", "#63b3ed", "#e879a6", "#b794f4"],
  defaultColor: "#f5c542",
  markStyle: "underline",
  popoverOnSelection: true,
  enableMarkdownHost: true,
  enableTranscriptHost: true,
  trackReplays: false,
  autoRevealPanel: true,
  resurfaceCount: 10,
  keepOrphanedSidecars: true
};
var AttentionSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Where to annotate").setHeading();
    new import_obsidian.Setting(containerEl).setName("Markdown notes").setDesc("Highlight and comment inside notes. The note itself is never modified.").addToggle(
      (t) => t.setValue(this.plugin.settings.enableMarkdownHost).onChange(async (v) => {
        this.plugin.settings.enableMarkdownHost = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Transcripts").setDesc(
      "Highlight and comment on transcript lines in the Media Transcript plugin. Has no effect if that plugin is not installed."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.enableTranscriptHost).onChange(async (v) => {
        this.plugin.settings.enableTranscriptHost = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Mark style").setDesc(
      "How highlights are drawn. Underline keeps a heavily-marked note readable and is easy to tell apart from Obsidian's own ==highlight== syntax. Annotations carrying a comment always get a little more weight."
    ).addDropdown(
      (d) => d.addOption("underline", "Underline").addOption("background", "Background").setValue(this.plugin.settings.markStyle).onChange(async (v) => {
        this.plugin.settings.markStyle = v;
        await this.plugin.saveSettings();
        this.plugin.applyMarkStyle();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show swatches on selection").setDesc(
      "Pop up the colour swatches as soon as you select text. Turn this off to capture only from the right-click menu, which stays available either way."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.popoverOnSelection).onChange(async (v) => {
        this.plugin.settings.popoverOnSelection = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Review").setHeading();
    new import_obsidian.Setting(containerEl).setName("Open the panel for annotated notes").setDesc(
      "Reveal the Attention panel when you open a note that has annotations, and leave it alone otherwise. Focus stays in the note either way."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.autoRevealPanel).onChange(async (v) => {
        this.plugin.settings.autoRevealPanel = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Resurface count").setDesc("How many annotations to bring back at a time, preferring ones you have not revisited.").addSlider(
      (s) => s.setLimits(3, 50, 1).setValue(this.plugin.settings.resurfaceCount).onChange(async (v) => {
        this.plugin.settings.resurfaceCount = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Advanced").setHeading();
    new import_obsidian.Setting(containerEl).setName("Count replays").setDesc(
      "Record how often you replay a transcript segment. A weaker signal than a highlight, but a much denser one \u2014 useful for spotting what actually held your attention."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.trackReplays).onChange(async (v) => {
        this.plugin.settings.trackReplays = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Keep annotations when a file is deleted").setDesc("Leaves the .anno.json behind so annotations survive an accidental delete.").addToggle(
      (t) => t.setValue(this.plugin.settings.keepOrphanedSidecars).onChange(async (v) => {
        this.plugin.settings.keepOrphanedSidecars = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Rebuild index").setDesc("Rescan every sidecar in the vault. Safe to run any time \u2014 the index is derived data.").addButton(
      (b) => b.setButtonText("Rebuild").onClick(async () => {
        await this.plugin.rebuildIndex();
      })
    );
  }
};

// src/store/paths.ts
var SIDECAR_SUFFIX = ".anno.json";
function sidecarPathFor(targetPath) {
  return targetPath + SIDECAR_SUFFIX;
}
function isSidecarPath(path) {
  return path.endsWith(SIDECAR_SUFFIX);
}
function targetPathFor(sidecarPath) {
  if (!isSidecarPath(sidecarPath))
    return null;
  const target = sidecarPath.slice(0, -SIDECAR_SUFFIX.length);
  if (target.length === 0 || isSidecarPath(target))
    return null;
  return target;
}

// src/store/sidecar.ts
var import_obsidian2 = require("obsidian");

// src/model.ts
function emptyFile(target) {
  return { version: 1, target, annotations: [] };
}
function newId() {
  return Math.random().toString(36).slice(2, 10);
}
function isComment(a) {
  return a.body !== null && a.body.trim().length > 0;
}

// src/store/sidecar.ts
async function loadSidecar(app, targetPath) {
  const file = app.vault.getAbstractFileByPath(sidecarPathFor(targetPath));
  if (!(file instanceof import_obsidian2.TFile))
    return emptyFile(targetPath);
  try {
    const parsed = JSON.parse(await app.vault.read(file));
    if (parsed && typeof parsed === "object" && Array.isArray(parsed.annotations)) {
      return { ...parsed, target: targetPath };
    }
  } catch (e) {
  }
  return emptyFile(targetPath);
}
async function saveSidecar(app, data) {
  const path = sidecarPathFor(data.target);
  const existing = app.vault.getAbstractFileByPath(path);
  if (data.annotations.length === 0) {
    if (existing instanceof import_obsidian2.TFile)
      await app.fileManager.trashFile(existing);
    return;
  }
  const body = JSON.stringify(data, null, 2);
  if (existing instanceof import_obsidian2.TFile)
    await app.vault.modify(existing, body);
  else
    await app.vault.create(path, body);
}

// src/store/review.ts
var BUCKET_ORDER = ["today", "week", "month", "older"];
var DAY = 864e5;
function bucketize(entries, now) {
  const out = { today: [], week: [], month: [], older: [] };
  for (const e of entries) {
    const age = now - Date.parse(e.annotation.created);
    if (age < DAY)
      out.today.push(e);
    else if (age < 7 * DAY)
      out.week.push(e);
    else if (age < 30 * DAY)
      out.month.push(e);
    else
      out.older.push(e);
  }
  return out;
}
function pickResurface(entries, n, rand) {
  const decorated = entries.map((entry) => ({ entry, jitter: rand() }));
  decorated.sort((a, b) => {
    const seen = a.entry.annotation.reviewed.length - b.entry.annotation.reviewed.length;
    if (seen !== 0)
      return seen;
    return a.jitter - b.jitter;
  });
  return decorated.slice(0, Math.max(0, n)).map((d) => d.entry);
}
function byNewest(a, b) {
  return b.annotation.created.localeCompare(a.annotation.created);
}

// src/store/attentionIndex.ts
var AttentionIndex = class {
  constructor(app) {
    this.app = app;
    this.entries = [];
  }
  /** Rescan every sidecar in the vault. Cheap enough to run on load. */
  async rebuild() {
    const next = [];
    for (const file of this.app.vault.getFiles()) {
      if (!isSidecarPath(file.path))
        continue;
      const targetPath = targetPathFor(file.path);
      if (!targetPath)
        continue;
      const data = await loadSidecar(this.app, targetPath);
      for (const annotation of data.annotations) {
        next.push({ targetPath, annotation });
      }
    }
    next.sort(byNewest);
    this.entries = next;
  }
  /** Replace one file's entries in place (after an edit, without a full scan). */
  replaceFile(targetPath, annotations) {
    this.entries = this.entries.filter((e) => e.targetPath !== targetPath);
    for (const annotation of annotations)
      this.entries.push({ targetPath, annotation });
    this.entries.sort(byNewest);
  }
  /** Follow a rename so the index doesn't point at a path that's gone. */
  renameFile(oldPath, newPath) {
    for (const e of this.entries) {
      if (e.targetPath === oldPath)
        e.targetPath = newPath;
    }
  }
  all() {
    return this.entries;
  }
  buckets(now = Date.now()) {
    return bucketize(this.entries, now);
  }
  resurface(n, rand) {
    return pickResurface(this.entries, n, rand);
  }
};

// src/views/ReviewView.ts
var import_obsidian4 = require("obsidian");

// src/anchor/textQuote.ts
var CONTEXT_LEN = 32;
function describe(text, from, to) {
  return {
    quote: text.slice(from, to),
    prefix: text.slice(Math.max(0, from - CONTEXT_LEN), from),
    suffix: text.slice(to, to + CONTEXT_LEN),
    from,
    to
  };
}
function commonSuffixLen(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[a.length - 1 - n] === b[b.length - 1 - n])
    n++;
  return n;
}
function commonPrefixLen(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[n] === b[n])
    n++;
  return n;
}
function allOccurrences(text, needle) {
  if (needle.length === 0)
    return [];
  const out = [];
  let at = text.indexOf(needle);
  while (at >= 0) {
    out.push(at);
    at = text.indexOf(needle, at + 1);
  }
  return out;
}
function resolve(text, anchor) {
  const { quote } = anchor;
  if (quote.length === 0)
    return null;
  if (text.slice(anchor.from, anchor.to) === quote) {
    return { from: anchor.from, to: anchor.to, how: "exact" };
  }
  const hits = allOccurrences(text, quote);
  if (hits.length === 0)
    return null;
  if (hits.length === 1) {
    return { from: hits[0], to: hits[0] + quote.length, how: "unique" };
  }
  let best = -1;
  let bestScore = -1;
  for (const at of hits) {
    const score = commonSuffixLen(text.slice(0, at), anchor.prefix) + commonPrefixLen(text.slice(at + quote.length), anchor.suffix);
    if (score > bestScore) {
      bestScore = score;
      best = at;
    }
  }
  if (bestScore > 0) {
    return { from: best, to: best + quote.length, how: "context" };
  }
  let nearest = hits[0];
  for (const at of hits) {
    if (Math.abs(at - anchor.from) < Math.abs(nearest - anchor.from))
      nearest = at;
  }
  return { from: nearest, to: nearest + quote.length, how: "nearest" };
}
function nthOccurrence(text, needle, n) {
  if (needle.length === 0 || n < 0)
    return -1;
  let at = text.indexOf(needle);
  for (let i = 0; i < n && at >= 0; i++)
    at = text.indexOf(needle, at + 1);
  return at;
}
function countOccurrences(before, needle) {
  if (needle.length === 0)
    return 0;
  let n = 0;
  let at = before.indexOf(needle);
  while (at >= 0) {
    n++;
    at = before.indexOf(needle, at + 1);
  }
  return n;
}

// src/store/documentOrder.ts
async function inDocumentOrder(app, file, annotations) {
  if (annotations.length === 0)
    return [];
  let source;
  try {
    source = await app.vault.cachedRead(file);
  } catch (e) {
    return [...annotations];
  }
  const positioned = annotations.map((a) => {
    var _a, _b;
    return {
      a,
      at: a.anchor.kind === "markdown" ? (_b = (_a = resolve(source, a.anchor)) == null ? void 0 : _a.from) != null ? _b : null : null
    };
  });
  return positioned.sort((x, y) => {
    if (x.at === null && y.at === null)
      return 0;
    if (x.at === null)
      return 1;
    if (y.at === null)
      return -1;
    return x.at - y.at;
  }).map((p) => p.a);
}

// src/hosts/markdown/reveal.ts
var import_obsidian3 = require("obsidian");
async function reveal(app, file, annotation) {
  if (annotation.anchor.kind === "transcript") {
    await revealInTranscript(app, file, annotation);
    return;
  }
  await revealInMarkdown(app, file, annotation);
}
async function revealInTranscript(app, file, annotation) {
  if (annotation.anchor.kind !== "transcript")
    return;
  const at = annotation.anchor.start;
  await app.workspace.getLeaf(false).openFile(file);
  for (let i = 0; i < 40; i++) {
    const media = document.querySelector(".mt-view video, .mt-view audio");
    if (media instanceof HTMLMediaElement) {
      const seek = () => {
        media.currentTime = at;
      };
      if (media.readyState > 0)
        seek();
      else
        media.addEventListener("loadedmetadata", seek, { once: true });
      void media.play();
      const painted = document.querySelector(`.at-hl[data-at-id="${annotation.id}"]`);
      if (painted instanceof HTMLElement) {
        painted.scrollIntoView({ behavior: "smooth", block: "center" });
        flash(painted);
      }
      return;
    }
    await new Promise((r) => window.setTimeout(r, 50));
  }
}
async function revealInMarkdown(app, file, annotation) {
  const leaf = app.workspace.getLeaf(false);
  await leaf.openFile(file);
  const view = leaf.view;
  if (!(view instanceof import_obsidian3.MarkdownView))
    return;
  if (view.getMode() === "source") {
    if (annotation.anchor.kind !== "markdown")
      return;
    const editor = view.editor;
    const at = resolve(editor.getValue(), annotation.anchor);
    if (!at)
      return;
    const from = editor.offsetToPos(at.from);
    const to = editor.offsetToPos(at.to);
    editor.setSelection(from, to);
    editor.scrollIntoView({ from, to }, true);
    return;
  }
  await flashWhenPainted(view, annotation.id);
}
async function flashWhenPainted(view, id, tries = 20) {
  for (let i = 0; i < tries; i++) {
    const el = view.contentEl.querySelector(`.at-hl[data-at-id="${id}"]`);
    if (el instanceof HTMLElement) {
      el.scrollIntoView({ behavior: "smooth", block: "center" });
      flash(el);
      return;
    }
    await new Promise((r) => window.setTimeout(r, 50));
  }
}
function flash(el) {
  el.addClass("at-flash");
  window.setTimeout(() => el.removeClass("at-flash"), 1300);
}

// src/views/ReviewView.ts
var VIEW_TYPE_REVIEW = "attention-review";
var BUCKET_LABELS = {
  today: "Today",
  week: "This week",
  month: "This month",
  older: "Earlier"
};
var ReviewView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.lens = "file";
    /**
     * Bumped on every render. Rendering empties the panel, then awaits a file
     * read before appending; two overlapping calls would each empty and then each
     * append, listing everything twice. A render whose generation has been
     * superseded stops instead of drawing.
     */
    this.generation = 0;
    this.resurfaced = null;
  }
  getViewType() {
    return VIEW_TYPE_REVIEW;
  }
  getDisplayText() {
    return "Attention";
  }
  getIcon() {
    return "highlighter";
  }
  async onOpen() {
    this.registerEvent(this.app.workspace.on("file-open", () => {
      void this.render();
    }));
    await this.render();
  }
  /** Re-render. Safe to call from anywhere; it reads current state itself. */
  async render() {
    const seq = ++this.generation;
    const root = this.contentEl;
    root.empty();
    root.addClass("at-review");
    this.renderHeader(root);
    if (this.resurfaced) {
      for (const e of this.resurfaced)
        this.renderEntry(root, e.annotation, e.targetPath);
      return;
    }
    if (this.lens === "file")
      await this.renderFile(root, seq);
    else
      this.renderAll(root);
  }
  renderHeader(root) {
    const header = root.createDiv("at-review-header");
    const tabs = header.createDiv("at-tabs");
    const tab = (label, lens) => {
      const el = tabs.createEl("button", { text: label, cls: "at-tab" });
      if (this.lens === lens && !this.resurfaced)
        el.addClass("is-active");
      el.addEventListener("click", () => {
        this.lens = lens;
        this.resurfaced = null;
        void this.render();
      });
    };
    tab("This note", "file");
    tab("All", "all");
    const resurface = header.createEl("button", { text: "Resurface", cls: "at-btn" });
    if (this.resurfaced)
      resurface.addClass("is-active");
    resurface.addEventListener("click", () => {
      this.resurfaced = this.resurfaced ? null : this.plugin.index.resurface(this.plugin.settings.resurfaceCount, () => Math.random());
      void this.render();
    });
  }
  // ── This note ──────────────────────────────────────────────────────────────
  async renderFile(root, seq) {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      this.empty(root, "No note open.");
      return;
    }
    const data = await this.plugin.store.get(file.path);
    if (seq !== this.generation)
      return;
    if (data.annotations.length === 0) {
      this.empty(root, `Nothing marked in \u201C${file.basename}\u201D.`);
      return;
    }
    const ordered = await inDocumentOrder(this.app, file, data.annotations);
    if (seq !== this.generation)
      return;
    root.createDiv("at-bucket-title").setText(`${ordered.length} in this note`);
    for (const a of ordered)
      this.renderEntry(root, a, file.path);
  }
  // ── All ────────────────────────────────────────────────────────────────────
  renderAll(root) {
    const buckets = this.plugin.index.buckets();
    const total = this.plugin.index.all().length;
    if (total === 0) {
      this.empty(root, "Nothing marked yet. Select text in a note to highlight it.");
      return;
    }
    for (const key of BUCKET_ORDER) {
      const entries = buckets[key];
      if (entries.length === 0)
        continue;
      root.createDiv("at-bucket-title").setText(`${BUCKET_LABELS[key]} \xB7 ${entries.length}`);
      for (const e of entries)
        this.renderEntry(root, e.annotation, e.targetPath);
    }
  }
  // ── Shared ─────────────────────────────────────────────────────────────────
  empty(root, message) {
    root.createDiv("at-empty").setText(message);
  }
  renderEntry(root, annotation, targetPath) {
    var _a, _b;
    const el = root.createDiv("at-entry");
    el.setCssProps({ "--at-color": annotation.color });
    el.createDiv("at-quote").setText(annotation.anchor.quote);
    if (isComment(annotation)) {
      el.createDiv("at-body").setText((_a = annotation.body) != null ? _a : "");
    }
    if (this.lens === "all" || this.resurfaced) {
      const meta = el.createDiv("at-meta");
      meta.createSpan({ text: (_b = targetPath.split("/").pop()) != null ? _b : targetPath, cls: "at-source" });
      if (annotation.anchor.kind === "transcript") {
        meta.createSpan({ text: fmtTime(annotation.anchor.start), cls: "at-time" });
      }
    }
    el.addEventListener("click", () => {
      void this.jumpTo(annotation, targetPath);
    });
  }
  // Named jumpTo, not open: View.prototype.open is what Obsidian calls to mount
  // a view, and shadowing it leaves the view constructed but never attached —
  // a panel that renders correctly into an element that is not in the document.
  async jumpTo(annotation, targetPath) {
    const file = this.app.vault.getAbstractFileByPath(targetPath);
    if (!(file instanceof import_obsidian4.TFile))
      return;
    await reveal(this.app, file, annotation);
    await this.plugin.markReviewed({ targetPath, annotation });
  }
};
function fmtTime(seconds) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

// src/store/annotationStore.ts
var AnnotationStore = class {
  constructor(app, index) {
    this.app = app;
    this.index = index;
    this.cache = /* @__PURE__ */ new Map();
    this.listeners = [];
    /** Paths with a warm already in flight, so a miss can't spawn a stampede. */
    this.warming = /* @__PURE__ */ new Set();
  }
  /** Annotations for a file, from cache when we have it. */
  async get(targetPath) {
    const cached = this.cache.get(targetPath);
    if (cached)
      return cached;
    const loaded = await loadSidecar(this.app, targetPath);
    this.cache.set(targetPath, loaded);
    return loaded;
  }
  /**
   * Synchronous read for render paths that can't await.
   *
   * A miss means a view is painting a file nobody has loaded yet — which used
   * to render as "this file has no annotations" and stay that way. So a miss
   * kicks off a load and notifies when it lands, turning a silent wrong answer
   * into a brief empty one.
   */
  peek(targetPath) {
    const cached = this.cache.get(targetPath);
    if (cached)
      return cached.annotations;
    if (!this.warming.has(targetPath)) {
      this.warming.add(targetPath);
      void this.get(targetPath).then(() => this.emit(targetPath)).finally(() => this.warming.delete(targetPath));
    }
    return [];
  }
  /** Load into the cache so a later peek() has something to paint. */
  async warm(targetPath) {
    await this.get(targetPath);
    this.emit(targetPath);
  }
  async add(targetPath, annotation) {
    const data = await this.get(targetPath);
    data.annotations.push(annotation);
    await this.commit(targetPath, data);
  }
  async update(targetPath, id, patch) {
    const data = await this.get(targetPath);
    const target = data.annotations.find((a) => a.id === id);
    if (!target)
      return;
    Object.assign(target, patch, { updated: new Date().toISOString() });
    await this.commit(targetPath, data);
  }
  async remove(targetPath, id) {
    const data = await this.get(targetPath);
    const before = data.annotations.length;
    data.annotations = data.annotations.filter((a) => a.id !== id);
    if (data.annotations.length === before)
      return;
    await this.commit(targetPath, data);
  }
  /** Drop a cache entry (after an external edit or a rename). */
  forget(targetPath) {
    this.cache.delete(targetPath);
  }
  async commit(targetPath, data) {
    await saveSidecar(this.app, data);
    this.cache.set(targetPath, data);
    this.index.replaceFile(targetPath, data.annotations);
    this.emit(targetPath);
  }
  onChange(listener) {
    this.listeners.push(listener);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== listener);
    };
  }
  emit(targetPath) {
    for (const l of this.listeners)
      l(targetPath);
  }
};

// src/hosts/markdown/MarkdownHost.ts
var import_obsidian6 = require("obsidian");

// src/ui/SelectionPopover.ts
var SelectionPopover = class {
  constructor(colors) {
    this.colors = colors;
    this.el = null;
    this.dismiss = () => this.hide();
  }
  showAt(rect, actions) {
    this.hide();
    const el = document.createElement("div");
    el.className = "at-popover";
    for (const color of this.colors) {
      const swatch = el.createEl("button", { cls: "at-swatch" });
      swatch.style.background = color;
      swatch.setAttribute("aria-label", `Highlight ${color}`);
      swatch.addEventListener("mousedown", (e) => {
        e.preventDefault();
        actions.onHighlight(color);
        this.hide();
      });
    }
    const comment = el.createEl("button", { cls: "at-pop-btn", text: "\u{1F4AC}" });
    comment.setAttribute("aria-label", "Add a comment");
    comment.addEventListener("mousedown", (e) => {
      e.preventDefault();
      actions.onComment();
      this.hide();
    });
    if (actions.onRemove) {
      const remove = el.createEl("button", { cls: "at-pop-btn", text: "\u2715" });
      remove.setAttribute("aria-label", "Remove highlight");
      remove.addEventListener("mousedown", (e) => {
        var _a;
        e.preventDefault();
        (_a = actions.onRemove) == null ? void 0 : _a.call(actions);
        this.hide();
      });
    }
    document.body.appendChild(el);
    this.el = el;
    const { width, height } = el.getBoundingClientRect();
    const left = Math.min(
      Math.max(8, rect.left + rect.width / 2 - width / 2),
      window.innerWidth - width - 8
    );
    const above = rect.top - height - 8;
    el.style.left = `${left}px`;
    el.style.top = `${above < 8 ? rect.bottom + 8 : above}px`;
    window.setTimeout(() => {
      document.addEventListener("mousedown", this.dismiss);
      document.addEventListener("keydown", this.dismiss);
    }, 0);
  }
  hide() {
    var _a;
    document.removeEventListener("mousedown", this.dismiss);
    document.removeEventListener("keydown", this.dismiss);
    (_a = this.el) == null ? void 0 : _a.remove();
    this.el = null;
  }
};

// src/ui/CommentBubble.ts
var CommentBubble = class {
  constructor() {
    this.el = null;
    this.dismiss = (e) => {
      var _a;
      if (e.target instanceof Node && ((_a = this.el) == null ? void 0 : _a.contains(e.target)))
        return;
      this.hide();
    };
  }
  showFor(rect, body, actions) {
    this.hide();
    const el = document.createElement("div");
    el.className = "at-bubble";
    if (body && body.trim().length > 0) {
      el.createDiv("at-bubble-body").setText(body);
    } else {
      el.createDiv("at-bubble-empty").setText("No comment yet.");
    }
    const row = el.createDiv("at-bubble-actions");
    const add = (label, fn, warn = false) => {
      const b = row.createEl("button", { cls: "at-pop-btn", text: label });
      if (warn)
        b.addClass("mod-warning");
      b.addEventListener("click", () => {
        fn();
        this.hide();
      });
    };
    add(body ? "Edit" : "Comment", actions.onEdit);
    add("Colour", actions.onRecolour);
    add("Remove", actions.onRemove, true);
    document.body.appendChild(el);
    this.el = el;
    const { width, height } = el.getBoundingClientRect();
    const left = Math.min(
      Math.max(8, rect.left + rect.width / 2 - width / 2),
      window.innerWidth - width - 8
    );
    const above = rect.top - height - 8;
    el.style.left = `${left}px`;
    el.style.top = `${above < 8 ? rect.bottom + 8 : above}px`;
    window.setTimeout(() => {
      document.addEventListener("mousedown", this.dismiss);
      document.addEventListener("keydown", this.dismiss);
    }, 0);
  }
  hide() {
    var _a;
    document.removeEventListener("mousedown", this.dismiss);
    document.removeEventListener("keydown", this.dismiss);
    (_a = this.el) == null ? void 0 : _a.remove();
    this.el = null;
  }
};

// src/ui/CommentModal.ts
var import_obsidian5 = require("obsidian");
var CommentModal = class extends import_obsidian5.Modal {
  constructor(app, quote, initial, onSubmit) {
    super(app);
    this.quote = quote;
    this.onSubmit = onSubmit;
    this.value = initial;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("at-comment-modal");
    contentEl.createDiv("at-comment-quote").setText(this.quote);
    const input = contentEl.createEl("textarea", { cls: "at-comment-input" });
    input.value = this.value;
    input.placeholder = "What caught your attention?";
    input.addEventListener("input", () => {
      this.value = input.value;
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        this.submit();
      }
    });
    new import_obsidian5.Setting(contentEl).addButton(
      (b) => b.setButtonText("Save").setCta().onClick(() => this.submit())
    );
    window.setTimeout(() => input.focus(), 0);
  }
  submit() {
    this.onSubmit(this.value.trim());
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/hosts/markdown/MarkdownHost.ts
var MarkdownHost = class {
  constructor(app, plugin, store, settings) {
    this.app = app;
    this.plugin = plugin;
    this.store = store;
    this.settings = settings;
    this.bubble = new CommentBubble();
    /** The element right-clicked, captured before any menu is built. */
    this.lastTarget = null;
    this.popover = new SelectionPopover(settings.colors);
  }
  register() {
    this.plugin.registerDomEvent(
      document,
      "contextmenu",
      (e) => {
        this.lastTarget = e.target instanceof HTMLElement ? e.target : null;
      },
      true
    );
    this.plugin.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, info) => {
        this.onEditorMenu(menu, editor, info);
      })
    );
    this.plugin.registerDomEvent(document, "mouseup", (e) => {
      if (e.button !== 0 || !this.settings.popoverOnSelection)
        return;
      if (e.target instanceof HTMLElement && e.target.closest(".at-hl, .at-popover, .at-bubble"))
        return;
      window.setTimeout(() => {
        void this.onSelectionMade();
      }, 0);
    });
    this.plugin.registerDomEvent(document, "click", (e) => {
      var _a, _b, _c;
      const hit = e.target instanceof HTMLElement ? e.target.closest(".at-hl") : null;
      if (!(hit instanceof HTMLElement))
        return;
      if (((_b = (_a = window.getSelection()) == null ? void 0 : _a.toString().trim().length) != null ? _b : 0) > 0)
        return;
      const file = (_c = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView)) == null ? void 0 : _c.file;
      if (file)
        void this.showBubble(file, hit);
    });
    this.plugin.registerDomEvent(document, "contextmenu", (e) => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
      if (!(view == null ? void 0 : view.file) || view.getMode() !== "preview")
        return;
      if (!this.hasSomethingToOffer(view))
        return;
      e.preventDefault();
      void this.showReadingMenu(e, view);
    });
  }
  detach() {
    this.popover.hide();
    this.bubble.hide();
  }
  async showBubble(file, el) {
    const id = el.dataset.atId;
    if (!id)
      return;
    const data = await this.store.get(file.path);
    const annotation = data.annotations.find((a) => a.id === id);
    if (!annotation)
      return;
    this.bubble.showFor(el.getBoundingClientRect(), annotation.body, {
      onEdit: () => {
        void this.editComment(file, id);
      },
      onRecolour: () => {
        this.popover.showAt(el.getBoundingClientRect(), {
          onHighlight: (color) => {
            void this.store.update(file.path, id, { color });
          },
          onComment: () => {
            void this.editComment(file, id);
          }
        });
      },
      onRemove: () => {
        void this.store.remove(file.path, id);
      }
    });
  }
  hasSomethingToOffer(view) {
    var _a, _b, _c;
    if ((_a = this.lastTarget) == null ? void 0 : _a.closest(".at-hl"))
      return true;
    const selection = window.getSelection();
    return ((_b = selection == null ? void 0 : selection.toString().trim().length) != null ? _b : 0) > 0 && view.contentEl.contains((_c = selection == null ? void 0 : selection.anchorNode) != null ? _c : null);
  }
  /** Anchor whatever is selected, whichever mode the view is in. */
  async capture(view) {
    if (view.getMode() === "source")
      return this.captureEditor(view.editor);
    return view.file ? this.captureRendered(view, view.file) : null;
  }
  captureEditor(editor) {
    const from = editor.posToOffset(editor.getCursor("from"));
    const to = editor.posToOffset(editor.getCursor("to"));
    if (from === to)
      return null;
    return { kind: "markdown", ...describe(editor.getValue(), from, to) };
  }
  /** Selection finished: offer the swatches straight away, if asked to. */
  async onSelectionMade() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    const file = view == null ? void 0 : view.file;
    if (!view || !file)
      return;
    const selection = window.getSelection();
    if (!selection || selection.toString().trim().length === 0)
      return;
    if (!view.contentEl.contains(selection.anchorNode))
      return;
    const rect = selection.getRangeAt(0).getBoundingClientRect();
    const anchor = await this.capture(view);
    if (!anchor)
      return;
    this.popover.showAt(rect, {
      onHighlight: (color) => {
        void this.create(file, anchor, color, null);
      },
      onComment: () => this.promptComment(file, anchor, "")
    });
  }
  // ── Editing modes ──────────────────────────────────────────────────────────
  onEditorMenu(menu, editor, info) {
    var _a;
    const file = info.file;
    if (!file)
      return;
    const existing = (_a = this.lastTarget) == null ? void 0 : _a.closest(".at-hl");
    if (existing instanceof HTMLElement) {
      this.addExistingItems(menu, file, existing);
      return;
    }
    const anchor = this.captureEditor(editor);
    if (anchor)
      this.addCreateItems(menu, file, anchor);
  }
  // ── Reading mode ───────────────────────────────────────────────────────────
  async showReadingMenu(e, view) {
    var _a;
    const file = view.file;
    if (!file)
      return;
    const menu = new import_obsidian6.Menu();
    const existing = (_a = this.lastTarget) == null ? void 0 : _a.closest(".at-hl");
    if (existing instanceof HTMLElement) {
      this.addExistingItems(menu, file, existing);
    } else {
      const anchor = await this.captureRendered(view, file);
      if (!anchor)
        return;
      this.addCreateItems(menu, file, anchor);
    }
    menu.showAtMouseEvent(e);
  }
  /** Locate a reading-mode selection in the source by ordinal. */
  async captureRendered(view, file) {
    var _a;
    const selection = window.getSelection();
    const selected = (_a = selection == null ? void 0 : selection.toString()) != null ? _a : "";
    if (!selection || selected.trim().length === 0)
      return null;
    const source = await this.app.vault.cachedRead(file);
    const at = nthOccurrence(source, selected, this.renderedOrdinal(view, selection, selected));
    if (at < 0) {
      new import_obsidian6.Notice("Attention: cannot anchor a selection that crosses formatting.");
      return null;
    }
    return { kind: "markdown", ...describe(source, at, at + selected.length) };
  }
  /** How many identical strings precede this selection on screen. */
  renderedOrdinal(view, selection, selected) {
    const sel = selection.getRangeAt(0);
    const before = sel.cloneRange();
    before.selectNodeContents(view.contentEl);
    before.setEnd(sel.startContainer, sel.startOffset);
    return countOccurrences(before.toString(), selected);
  }
  // ── Menu items ─────────────────────────────────────────────────────────────
  addCreateItems(menu, file, anchor) {
    menu.addItem(
      (item) => item.setTitle("Highlight").setIcon("highlighter").onClick(() => {
        void this.create(file, anchor, this.settings.defaultColor, null);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Highlight in colour\u2026").setIcon("palette").onClick((e) => {
        this.popover.showAt(rectOf(e), {
          onHighlight: (color) => {
            void this.create(file, anchor, color, null);
          },
          onComment: () => this.promptComment(file, anchor, "")
        });
      })
    );
    menu.addItem(
      (item) => item.setTitle("Comment\u2026").setIcon("message-square").onClick(() => this.promptComment(file, anchor, ""))
    );
  }
  addExistingItems(menu, file, el) {
    const id = el.dataset.atId;
    if (!id)
      return;
    menu.addItem(
      (item) => item.setTitle("Edit comment\u2026").setIcon("message-square").onClick(() => {
        void this.editComment(file, id);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Change colour\u2026").setIcon("palette").onClick(() => {
        this.popover.showAt(el.getBoundingClientRect(), {
          onHighlight: (color) => {
            void this.store.update(file.path, id, { color });
          },
          onComment: () => {
            void this.editComment(file, id);
          }
        });
      })
    );
    menu.addItem(
      (item) => item.setTitle("Remove highlight").setIcon("trash").setWarning(true).onClick(() => {
        void this.store.remove(file.path, id);
      })
    );
  }
  // ── Actions ────────────────────────────────────────────────────────────────
  promptComment(file, anchor, initial) {
    new CommentModal(this.app, anchor.quote, initial, (body) => {
      void this.create(file, anchor, this.settings.defaultColor, body || null);
    }).open();
  }
  async editComment(file, id) {
    var _a;
    const data = await this.store.get(file.path);
    const annotation = data.annotations.find((a) => a.id === id);
    if (!annotation)
      return;
    new CommentModal(this.app, annotation.anchor.quote, (_a = annotation.body) != null ? _a : "", (body) => {
      void this.store.update(file.path, id, { body: body || null });
    }).open();
  }
  async create(file, anchor, color, body) {
    const annotation = {
      id: newId(),
      anchor,
      color,
      body,
      created: new Date().toISOString(),
      reviewed: []
    };
    await this.store.add(file.path, annotation);
  }
};
function rectOf(e) {
  const x = e instanceof MouseEvent ? e.clientX : window.innerWidth / 2;
  const y = e instanceof MouseEvent ? e.clientY : window.innerHeight / 2;
  return new DOMRect(x, y, 0, 0);
}

// src/hosts/markdown/decorations.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_obsidian7 = require("obsidian");
var refreshAnnotations = import_state.StateEffect.define();
function build(view, provider) {
  var _a, _b;
  const path = (_b = (_a = view.state.field(import_obsidian7.editorInfoField, false)) == null ? void 0 : _a.file) == null ? void 0 : _b.path;
  if (!path)
    return import_view.Decoration.none;
  const annotations = provider(path);
  if (annotations.length === 0)
    return import_view.Decoration.none;
  const doc = view.state.doc.toString();
  const ranges = [];
  for (const a of annotations) {
    if (a.anchor.kind !== "markdown")
      continue;
    const at = resolve(doc, a.anchor);
    if (!at || at.from === at.to)
      continue;
    ranges.push(
      import_view.Decoration.mark({
        class: isComment(a) ? "at-hl at-hl-comment" : "at-hl",
        attributes: { style: `--at-color: ${a.color}`, "data-at-id": a.id }
      }).range(at.from, at.to)
    );
  }
  return import_view.Decoration.set(ranges, true);
}
function annotationDecorations(provider) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = build(view, provider);
      }
      update(u) {
        const refreshed = u.transactions.some(
          (t) => t.effects.some((e) => e.is(refreshAnnotations))
        );
        if (u.docChanged || u.viewportChanged || refreshed) {
          this.decorations = build(u.view, provider);
        }
      }
    },
    { decorations: (v) => v.decorations }
  );
}
function repaintEditors(app) {
  app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
    const view = leaf.view;
    if (!(view instanceof import_obsidian7.MarkdownView))
      return;
    const cm = view.editor.cm;
    cm == null ? void 0 : cm.dispatch({ effects: refreshAnnotations.of() });
  });
}

// src/hosts/paintQuote.ts
function paintQuote(root, annotation, quote = annotation.anchor.quote) {
  if (!quote)
    return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const targets = [];
  for (let n = walker.nextNode(); n; n = walker.nextNode()) {
    const text = n;
    if (text.data.includes(quote) && !isInsideHighlight(text))
      targets.push(text);
  }
  for (const node of targets) {
    const at = node.data.indexOf(quote);
    if (at < 0)
      continue;
    const tail = node.splitText(at);
    tail.splitText(quote.length);
    const span = document.createElement("span");
    span.className = isComment(annotation) ? "at-hl at-hl-comment" : "at-hl";
    span.style.setProperty("--at-color", annotation.color);
    span.dataset.atId = annotation.id;
    tail.replaceWith(span);
    span.appendChild(tail);
  }
}
function isInsideHighlight(node) {
  var _a;
  return ((_a = node.parentElement) == null ? void 0 : _a.closest(".at-hl")) != null;
}

// src/hosts/markdown/readingMode.ts
function readingModeHighlighter(provider) {
  return (el, ctx) => {
    const annotations = provider(ctx.sourcePath);
    if (annotations.length === 0)
      return;
    for (const a of annotations) {
      if (a.anchor.kind !== "markdown")
        continue;
      paintQuote(el, a);
    }
  };
}

// src/hosts/transcript/TranscriptHost.ts
var import_obsidian8 = require("obsidian");

// src/anchor/transcriptAnchor.ts
var TIME_TOLERANCE_S = 3;
function describeTranscript(seg, charStart, charEnd, track, contextLen = 32) {
  return {
    kind: "transcript",
    track,
    seg: seg.seg,
    start: seg.start,
    charStart,
    charEnd,
    quote: seg.text.slice(charStart, charEnd),
    prefix: seg.text.slice(Math.max(0, charStart - contextLen), charStart),
    suffix: seg.text.slice(charEnd, charEnd + contextLen)
  };
}
function commonSuffixLen2(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[a.length - 1 - n] === b[b.length - 1 - n])
    n++;
  return n;
}
function commonPrefixLen2(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[n] === b[n])
    n++;
  return n;
}
function resolveTranscript(segs, anchor, currentTrack) {
  if (!anchor.quote)
    return null;
  const sameTrack = currentTrack != null && currentTrack === anchor.track;
  if (sameTrack) {
    const seg = segs.find((s) => s.seg === anchor.seg);
    if (seg) {
      if (seg.text.slice(anchor.charStart, anchor.charEnd) === anchor.quote) {
        return { seg: seg.seg, charStart: anchor.charStart, charEnd: anchor.charEnd, how: "exact" };
      }
      const at = seg.text.indexOf(anchor.quote);
      if (at >= 0) {
        return { seg: seg.seg, charStart: at, charEnd: at + anchor.quote.length, how: "drifted" };
      }
    }
  }
  const near = segs.filter((s) => Math.abs(s.start - anchor.start) <= TIME_TOLERANCE_S);
  const scored = [];
  for (const s of near) {
    const at = s.text.indexOf(anchor.quote);
    if (at < 0)
      continue;
    scored.push({
      seg: s,
      at,
      score: commonSuffixLen2(s.text.slice(0, at), anchor.prefix) + commonPrefixLen2(s.text.slice(at + anchor.quote.length), anchor.suffix)
    });
  }
  if (scored.length > 0) {
    scored.sort((a, b) => b.score - a.score || Math.abs(a.seg.start - anchor.start) - Math.abs(b.seg.start - anchor.start));
    const best = scored[0];
    return {
      seg: best.seg.seg,
      charStart: best.at,
      charEnd: best.at + anchor.quote.length,
      how: "retimed"
    };
  }
  const everywhere = segs.filter((s) => s.text.includes(anchor.quote));
  if (everywhere.length === 1) {
    const s = everywhere[0];
    const at = s.text.indexOf(anchor.quote);
    return { seg: s.seg, charStart: at, charEnd: at + anchor.quote.length, how: "unique" };
  }
  return null;
}

// src/hosts/transcript/TranscriptHost.ts
var TRANSCRIPT_RENDERED = "mt:transcript-rendered";
var TranscriptHost = class {
  constructor(app, plugin, store, settings) {
    this.app = app;
    this.plugin = plugin;
    this.store = store;
    this.settings = settings;
    this.bubble = new CommentBubble();
    this.popover = new SelectionPopover(settings.colors);
  }
  register() {
    const onRendered = (e) => {
      var _a;
      const detail = e.detail;
      if (!(detail == null ? void 0 : detail.mediaPath))
        return;
      const panel = e.target instanceof HTMLElement ? (_a = e.target.querySelector(".mt-transcript")) != null ? _a : e.target : null;
      if (panel instanceof HTMLElement)
        void this.repaint(panel);
    };
    document.addEventListener(TRANSCRIPT_RENDERED, onRendered);
    this.plugin.register(() => document.removeEventListener(TRANSCRIPT_RENDERED, onRendered));
    this.plugin.register(this.store.onChange((path) => this.repaintOpenPanels(path)));
    this.plugin.registerDomEvent(document, "mouseup", (e) => {
      if (e.button !== 0 || !this.settings.popoverOnSelection)
        return;
      if (!this.inTranscript(e.target))
        return;
      if (e.target instanceof HTMLElement && e.target.closest(".at-hl, .at-popover, .at-bubble"))
        return;
      window.setTimeout(() => {
        void this.onSelectionMade();
      }, 0);
    });
    this.plugin.registerDomEvent(document, "click", (e) => {
      var _a, _b;
      const hit = e.target instanceof HTMLElement ? e.target.closest(".at-hl") : null;
      if (!(hit instanceof HTMLElement) || !this.inTranscript(hit))
        return;
      if (((_b = (_a = window.getSelection()) == null ? void 0 : _a.toString().trim().length) != null ? _b : 0) > 0)
        return;
      void this.showBubble(hit);
    });
    const onContextMenu = (e) => {
      var _a, _b;
      if (!this.inTranscript(e.target))
        return;
      const hit = e.target instanceof HTMLElement ? e.target.closest(".at-hl") : null;
      const selected = (_b = (_a = window.getSelection()) == null ? void 0 : _a.toString().trim()) != null ? _b : "";
      if (!hit && selected.length === 0)
        return;
      e.preventDefault();
      e.stopPropagation();
      void this.showMenu(e, hit instanceof HTMLElement ? hit : null);
    };
    document.addEventListener("contextmenu", onContextMenu, true);
    this.plugin.register(() => document.removeEventListener("contextmenu", onContextMenu, true));
  }
  detach() {
    this.popover.hide();
    this.bubble.hide();
  }
  inTranscript(target) {
    return this.panelOf(target) != null;
  }
  /**
   * The transcript panel containing `target`, and what it is showing.
   *
   * Read from the DOM rather than remembered from the announcement: a plugin
   * enabled while a transcript is already open never sees that event, and state
   * kept only in a handler is state you can miss.
   */
  panelOf(target) {
    var _a, _b;
    if (!(target instanceof HTMLElement))
      return null;
    const panel = target.closest(".mt-transcript");
    if (!(panel instanceof HTMLElement))
      return null;
    const mediaPath = (_a = panel.dataset.mtMedia) != null ? _a : "";
    if (!mediaPath)
      return null;
    return { panel, mediaPath, trackPath: (_b = panel.dataset.mtTrack) != null ? _b : "" };
  }
  // ── Painting ───────────────────────────────────────────────────────────────
  /** Read the transcript out of the DOM the other plugin rendered. */
  readSegments(panel) {
    const out = [];
    for (const el of Array.from(panel.querySelectorAll(".mt-segment"))) {
      if (!(el instanceof HTMLElement))
        continue;
      const txt = el.querySelector(".mt-txt");
      const seg = Number(el.dataset.mtSeg);
      const start = Number(el.dataset.mtStart);
      if (!(txt instanceof HTMLElement) || !Number.isFinite(seg))
        continue;
      out.push({ el, txt, seg: { seg, start, text: txt.innerText } });
    }
    return out;
  }
  async repaint(panel) {
    var _a;
    const mediaPath = panel.dataset.mtMedia;
    if (!mediaPath)
      return;
    const lines = this.readSegments(panel);
    if (lines.length === 0)
      return;
    const data = await this.store.get(mediaPath);
    const segs = lines.map((l) => l.seg);
    const track = (_a = panel.dataset.mtTrack) != null ? _a : null;
    for (const a of data.annotations) {
      if (a.anchor.kind !== "transcript")
        continue;
      const hit = resolveTranscript(segs, a.anchor, track);
      if (!hit)
        continue;
      const line = lines.find((l) => l.seg.seg === hit.seg);
      if (line)
        paintQuote(line.txt, a, line.seg.text.slice(hit.charStart, hit.charEnd));
    }
  }
  repaintOpenPanels(mediaPath) {
    for (const panel of Array.from(document.querySelectorAll(".mt-transcript"))) {
      if (panel instanceof HTMLElement && panel.dataset.mtMedia === mediaPath) {
        void this.repaint(panel);
      }
    }
  }
  // ── Capture ────────────────────────────────────────────────────────────────
  /** Turn the current selection into an anchor, if it sits inside one line. */
  capture() {
    var _a, _b;
    const selection = window.getSelection();
    const selected = (_a = selection == null ? void 0 : selection.toString()) != null ? _a : "";
    if (!selection || selected.trim().length === 0)
      return null;
    const node = selection.anchorNode;
    const el = (_b = node instanceof HTMLElement ? node : node == null ? void 0 : node.parentElement) != null ? _b : null;
    const where = this.panelOf(el);
    if (!where)
      return null;
    const segEl = el == null ? void 0 : el.closest(".mt-segment");
    const txt = segEl == null ? void 0 : segEl.querySelector(".mt-txt");
    if (!(segEl instanceof HTMLElement) || !(txt instanceof HTMLElement))
      return null;
    const text = txt.innerText;
    const at = text.indexOf(selected);
    if (at < 0) {
      new import_obsidian8.Notice("Attention: select within a single transcript line.");
      return null;
    }
    const seg = {
      seg: Number(segEl.dataset.mtSeg),
      start: Number(segEl.dataset.mtStart),
      text
    };
    return {
      anchor: describeTranscript(seg, at, at + selected.length, where.trackPath),
      mediaPath: where.mediaPath
    };
  }
  async onSelectionMade() {
    const captured = this.capture();
    if (!captured)
      return;
    const selection = window.getSelection();
    if (!selection || selection.rangeCount === 0)
      return;
    this.popover.showAt(selection.getRangeAt(0).getBoundingClientRect(), {
      onHighlight: (color) => {
        void this.create(captured.mediaPath, captured.anchor, color, null);
      },
      onComment: () => {
        new CommentModal(this.app, captured.anchor.quote, "", (body) => {
          void this.create(captured.mediaPath, captured.anchor, this.settings.defaultColor, body || null);
        }).open();
      }
    });
  }
  async showMenu(e, hit) {
    var _a;
    const menu = new import_obsidian8.Menu();
    if (hit) {
      const mediaPath = (_a = this.panelOf(hit)) == null ? void 0 : _a.mediaPath;
      const id = hit.dataset.atId;
      if (!mediaPath || !id)
        return;
      menu.addItem((i) => i.setTitle("Edit comment\u2026").setIcon("message-square").onClick(() => {
        void this.editComment(mediaPath, id);
      }));
      menu.addItem((i) => i.setTitle("Change colour\u2026").setIcon("palette").onClick(() => {
        this.popover.showAt(hit.getBoundingClientRect(), {
          onHighlight: (color) => {
            void this.store.update(mediaPath, id, { color });
          },
          onComment: () => {
            void this.editComment(mediaPath, id);
          }
        });
      }));
      menu.addItem((i) => i.setTitle("Remove highlight").setIcon("trash").setWarning(true).onClick(() => {
        void this.store.remove(mediaPath, id);
      }));
    } else {
      const captured = this.capture();
      if (!captured)
        return;
      menu.addItem((i) => i.setTitle("Highlight").setIcon("highlighter").onClick(() => {
        void this.create(captured.mediaPath, captured.anchor, this.settings.defaultColor, null);
      }));
      menu.addItem((i) => i.setTitle("Comment\u2026").setIcon("message-square").onClick(() => {
        new CommentModal(this.app, captured.anchor.quote, "", (body) => {
          void this.create(captured.mediaPath, captured.anchor, this.settings.defaultColor, body || null);
        }).open();
      }));
    }
    menu.showAtMouseEvent(e);
  }
  // ── Actions ────────────────────────────────────────────────────────────────
  async showBubble(el) {
    var _a;
    const mediaPath = (_a = this.panelOf(el)) == null ? void 0 : _a.mediaPath;
    const id = el.dataset.atId;
    if (!mediaPath || !id)
      return;
    const data = await this.store.get(mediaPath);
    const annotation = data.annotations.find((a) => a.id === id);
    if (!annotation)
      return;
    this.bubble.showFor(el.getBoundingClientRect(), annotation.body, {
      onEdit: () => {
        void this.editComment(mediaPath, id);
      },
      onRecolour: () => {
        this.popover.showAt(el.getBoundingClientRect(), {
          onHighlight: (color) => {
            void this.store.update(mediaPath, id, { color });
          },
          onComment: () => {
            void this.editComment(mediaPath, id);
          }
        });
      },
      onRemove: () => {
        void this.store.remove(mediaPath, id);
      }
    });
  }
  async editComment(mediaPath, id) {
    var _a;
    const data = await this.store.get(mediaPath);
    const annotation = data.annotations.find((a) => a.id === id);
    if (!annotation)
      return;
    new CommentModal(this.app, annotation.anchor.quote, (_a = annotation.body) != null ? _a : "", (body) => {
      void this.store.update(mediaPath, id, { body: body || null });
    }).open();
  }
  async create(mediaPath, anchor, color, body) {
    const annotation = {
      id: newId(),
      anchor,
      color,
      body,
      created: new Date().toISOString(),
      reviewed: []
    };
    await this.store.add(mediaPath, annotation);
  }
};

// src/main.ts
var AttentionPlugin = class extends import_obsidian9.Plugin {
  constructor() {
    super(...arguments);
    this.markdownHost = null;
    this.transcriptHost = null;
    /**
     * Show the panel. `focus: false` is used when opening it on the user's behalf
     * — revealing a sidebar is helpful, stealing the cursor mid-sentence is not.
     */
    this.opening = null;
  }
  async onload() {
    await this.loadSettings();
    this.index = new AttentionIndex(this.app);
    this.store = new AnnotationStore(this.app, this.index);
    this.registerView(VIEW_TYPE_REVIEW, (leaf) => new ReviewView(leaf, this));
    this.applyMarkStyle();
    if (this.settings.enableMarkdownHost)
      this.setupMarkdownHost();
    if (this.settings.enableTranscriptHost) {
      this.transcriptHost = new TranscriptHost(this.app, this, this.store, this.settings);
      this.transcriptHost.register();
    }
    this.register(this.store.onChange(() => {
      repaintEditors(this.app);
      this.rerenderReadingViews();
      this.refreshReviewViews();
    }));
    this.registerEvent(this.app.workspace.on("file-open", (file) => {
      if (file)
        void this.onFileOpen(file);
    }));
    this.app.workspace.onLayoutReady(() => {
      void this.onLayoutReady();
    });
    this.addRibbonIcon("highlighter", "Attention", () => {
      void this.openReview();
    });
    this.addCommand({
      id: "open-review",
      name: "Open attention review",
      callback: () => {
        void this.openReview();
      }
    });
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      void this.handleRename(file, oldPath);
    }));
    this.registerEvent(this.app.vault.on("delete", (file) => {
      void this.handleDelete(file);
    }));
    this.addSettingTab(new AttentionSettingTab(this.app, this));
  }
  /** Mark style is a body class, so switching it needs no repaint. */
  applyMarkStyle() {
    document.body.toggleClass("at-style-background", this.settings.markStyle === "background");
  }
  async onLayoutReady() {
    await this.rebuildIndex();
    await this.warmOpenFiles();
  }
  async warmOpenFiles() {
    const paths = /* @__PURE__ */ new Set();
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      const file = leaf.view instanceof import_obsidian9.MarkdownView ? leaf.view.file : null;
      if (file)
        paths.add(file.path);
    });
    await Promise.all([...paths].map((p) => this.store.warm(p)));
  }
  async onFileOpen(file) {
    await this.store.warm(file.path);
    if (!this.settings.autoRevealPanel)
      return;
    if (this.store.peek(file.path).length === 0)
      return;
    await this.openReview({ focus: false });
  }
  setupMarkdownHost() {
    const provider = (path) => this.store.peek(path);
    this.registerEditorExtension(annotationDecorations(provider));
    this.registerMarkdownPostProcessor(readingModeHighlighter(provider));
    this.markdownHost = new MarkdownHost(this.app, this, this.store, this.settings);
    this.markdownHost.register();
  }
  /** Reading mode caches its HTML, so post-processors only re-run on request. */
  rerenderReadingViews() {
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const view = leaf.view;
      if (view instanceof import_obsidian9.MarkdownView && view.getMode() === "preview") {
        view.previewMode.rerender(true);
      }
    }
  }
  async rebuildIndex() {
    await this.index.rebuild();
    this.refreshReviewViews();
  }
  /** Record that an annotation resurfaced, so future picks can prefer others. */
  async markReviewed(entry) {
    const data = await loadSidecar(this.app, entry.targetPath);
    const target = data.annotations.find((a) => a.id === entry.annotation.id);
    if (!target)
      return;
    target.reviewed.push(new Date().toISOString());
    await saveSidecar(this.app, data);
    this.index.replaceFile(entry.targetPath, data.annotations);
  }
  async openReview(opts = {}) {
    var _a;
    this.opening = ((_a = this.opening) != null ? _a : Promise.resolve()).then(() => this.doOpenReview(opts));
    return this.opening;
  }
  async doOpenReview({ focus = true } = {}) {
    var _a;
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_REVIEW);
    const leaf = (_a = existing[0]) != null ? _a : this.app.workspace.getRightLeaf(false);
    if (!leaf)
      return;
    if (!(leaf.view instanceof ReviewView)) {
      await leaf.setViewState({ type: VIEW_TYPE_REVIEW, active: focus });
    }
    await leaf.loadIfDeferred();
    await this.app.workspace.revealLeaf(leaf);
    if (!focus) {
      const editor = this.app.workspace.getActiveViewOfType(import_obsidian9.MarkdownView);
      if (editor)
        this.app.workspace.setActiveLeaf(editor.leaf, { focus: true });
    }
  }
  refreshReviewViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_REVIEW)) {
      if (leaf.isDeferred)
        continue;
      if (!leaf.view.containerEl.isConnected)
        continue;
      if (leaf.view instanceof ReviewView)
        void leaf.view.render();
    }
  }
  /**
   * Keep the sidecar beside its target. Folder moves need no work — the sidecar
   * is a sibling, so it travels with the folder — only a file's own rename does.
   */
  async handleRename(file, oldPath) {
    if (!(file instanceof import_obsidian9.TFile) || isSidecarPath(file.path))
      return;
    const old = this.app.vault.getAbstractFileByPath(sidecarPathFor(oldPath));
    if (!(old instanceof import_obsidian9.TFile))
      return;
    const nextPath = sidecarPathFor(file.path);
    if (old.path === nextPath)
      return;
    try {
      await this.app.fileManager.renameFile(old, nextPath);
      const data = await loadSidecar(this.app, file.path);
      await saveSidecar(this.app, data);
      this.store.forget(oldPath);
      this.index.renameFile(oldPath, file.path);
      this.refreshReviewViews();
    } catch (e) {
      new import_obsidian9.Notice(`Attention: could not move annotations for ${file.name}`);
      console.error(e);
    }
  }
  async handleDelete(file) {
    if (!(file instanceof import_obsidian9.TFile) || isSidecarPath(file.path))
      return;
    if (this.settings.keepOrphanedSidecars)
      return;
    const sidecar = this.app.vault.getAbstractFileByPath(sidecarPathFor(file.path));
    if (sidecar instanceof import_obsidian9.TFile)
      await this.app.fileManager.trashFile(sidecar);
    this.store.forget(file.path);
    this.index.replaceFile(file.path, []);
    this.refreshReviewViews();
  }
  onunload() {
    var _a, _b;
    (_a = this.markdownHost) == null ? void 0 : _a.detach();
    (_b = this.transcriptHost) == null ? void 0 : _b.detach();
    document.body.removeClass("at-style-background");
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved != null ? saved : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
