/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AttentionPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian12 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/ui/time.ts
var import_obsidian = require("obsidian");
var asMoment = import_obsidian.moment;
function formatWhen(iso, format = "", now) {
  const m = asMoment(iso);
  if (!m.isValid())
    return iso;
  if (format.trim().length > 0)
    return m.format(format);
  return now === void 0 ? m.fromNow() : m.from(asMoment(now));
}
var TIME_FORMAT_EXAMPLES = [
  "YYYY-MM-DD HH:mm:ss",
  "YYYY-MM-DD HH:mm",
  "YYYY-MM-DD"
];

// src/settings.ts
var DEFAULT_SETTINGS = {
  markColor: "#f5c542",
  markStyle: "underline",
  timeFormat: "YYYY-MM-DD HH:mm:ss",
  popoverOnSelection: true,
  enableMarkdownHost: true,
  enableTranscriptHost: true,
  trackReplays: false,
  autoRevealPanel: true,
  resurfaceCount: 10,
  keepOrphanedSidecars: true
};
var AttentionSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Appearance").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Mark colour").setDesc("Marks share one colour. A passage marked more than once is drawn more strongly.").addColorPicker(
      (c) => c.setValue(this.plugin.settings.markColor).onChange(async (v) => {
        this.plugin.settings.markColor = v;
        await this.plugin.saveSettings();
        this.plugin.applyMarkColor();
      })
    );
    const sample = new Date().toISOString();
    const timeSetting = new import_obsidian2.Setting(containerEl).setName("Time format").addText(
      (t) => t.setPlaceholder("empty = relative").setValue(this.plugin.settings.timeFormat).onChange(async (v) => {
        this.plugin.settings.timeFormat = v.trim();
        await this.plugin.saveSettings();
        describeTime();
        this.plugin.refreshPanels();
      })
    );
    const describeTime = () => {
      const f = this.plugin.settings.timeFormat;
      timeSetting.setDesc(
        `Shown as: ${formatWhen(sample, f)}. ` + (f ? `A moment format string \u2014 the same vocabulary as daily note filenames. Clear it for relative times ("3 days ago"), in your Obsidian's language.` : `Relative, and in your Obsidian's language. For an exact time, try ${TIME_FORMAT_EXAMPLES.join(" / ")}.`)
      );
    };
    describeTime();
    new import_obsidian2.Setting(containerEl).setName("Where to annotate").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Markdown notes").setDesc("Highlight and comment inside notes. The note itself is never modified.").addToggle(
      (t) => t.setValue(this.plugin.settings.enableMarkdownHost).onChange(async (v) => {
        this.plugin.settings.enableMarkdownHost = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Transcripts").setDesc(
      "Highlight and comment on transcript lines in the Media Transcript plugin. Has no effect if that plugin is not installed."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.enableTranscriptHost).onChange(async (v) => {
        this.plugin.settings.enableTranscriptHost = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Mark style").setDesc(
      "How highlights are drawn. Underline keeps a heavily-marked note readable and is easy to tell apart from Obsidian's own ==highlight== syntax. Annotations carrying a comment always get a little more weight."
    ).addDropdown(
      (d) => d.addOption("underline", "Underline").addOption("background", "Background").setValue(this.plugin.settings.markStyle).onChange(async (v) => {
        this.plugin.settings.markStyle = v;
        await this.plugin.saveSettings();
        this.plugin.applyMarkStyle();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Show swatches on selection").setDesc(
      "Pop up the colour swatches as soon as you select text. Turn this off to capture only from the right-click menu, which stays available either way."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.popoverOnSelection).onChange(async (v) => {
        this.plugin.settings.popoverOnSelection = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Review").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Open the panel for annotated notes").setDesc(
      "Reveal the Attention panel when you open a note that has annotations, and leave it alone otherwise. Focus stays in the note either way."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.autoRevealPanel).onChange(async (v) => {
        this.plugin.settings.autoRevealPanel = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Resurface count").setDesc("How many annotations to bring back at a time, preferring ones you have not revisited.").addSlider(
      (s) => s.setLimits(3, 50, 1).setValue(this.plugin.settings.resurfaceCount).onChange(async (v) => {
        this.plugin.settings.resurfaceCount = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Advanced").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Count replays").setDesc(
      "Record how often you replay a transcript segment. A weaker signal than a highlight, but a much denser one \u2014 useful for spotting what actually held your attention."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.trackReplays).onChange(async (v) => {
        this.plugin.settings.trackReplays = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Keep annotations when a file is deleted").setDesc("Leaves the .anno.json behind so annotations survive an accidental delete.").addToggle(
      (t) => t.setValue(this.plugin.settings.keepOrphanedSidecars).onChange(async (v) => {
        this.plugin.settings.keepOrphanedSidecars = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Rebuild index").setDesc("Rescan every sidecar in the vault. Safe to run any time \u2014 the index is derived data.").addButton(
      (b) => b.setButtonText("Rebuild").onClick(async () => {
        await this.plugin.rebuildIndex();
      })
    );
  }
};

// src/store/paths.ts
var SIDECAR_SUFFIX = ".anno.json";
function sidecarPathFor(targetPath) {
  return targetPath + SIDECAR_SUFFIX;
}
function isSidecarPath(path) {
  return path.endsWith(SIDECAR_SUFFIX);
}
function targetPathFor(sidecarPath) {
  if (!isSidecarPath(sidecarPath))
    return null;
  const target = sidecarPath.slice(0, -SIDECAR_SUFFIX.length);
  if (target.length === 0 || isSidecarPath(target))
    return null;
  return target;
}

// src/store/sidecar.ts
var import_obsidian3 = require("obsidian");

// src/model.ts
function firstMarked(a) {
  var _a;
  return (_a = a.hits[0]) != null ? _a : "";
}
function lastMarked(a) {
  var _a;
  return (_a = a.hits[a.hits.length - 1]) != null ? _a : "";
}
function normalize(raw) {
  var _a;
  if (Array.isArray(raw.hits) && raw.hits.length > 0)
    return raw;
  const created = (_a = raw.created) != null ? _a : new Date().toISOString();
  return { ...raw, hits: [created] };
}
function emptyFile(target) {
  return { version: 1, target, annotations: [] };
}
function newId() {
  return Math.random().toString(36).slice(2, 10);
}
function isComment(a) {
  return a.body !== null && a.body.trim().length > 0;
}
function sameSpot(a, b) {
  if (a.kind !== b.kind)
    return false;
  if (a.quote !== b.quote)
    return false;
  if (a.kind === "markdown" && b.kind === "markdown") {
    return a.from < b.to && b.from < a.to;
  }
  if (a.kind === "transcript" && b.kind === "transcript") {
    return a.seg === b.seg || Math.abs(a.start - b.start) < 0.5;
  }
  return false;
}

// src/store/sidecar.ts
async function loadSidecar(app, targetPath) {
  const file = app.vault.getAbstractFileByPath(sidecarPathFor(targetPath));
  if (!(file instanceof import_obsidian3.TFile))
    return emptyFile(targetPath);
  try {
    const parsed = JSON.parse(await app.vault.read(file));
    if (parsed && typeof parsed === "object" && Array.isArray(parsed.annotations)) {
      const file2 = parsed;
      return { ...file2, target: targetPath, annotations: file2.annotations.map(normalize) };
    }
  } catch (e) {
  }
  return emptyFile(targetPath);
}
async function saveSidecar(app, data) {
  const path = sidecarPathFor(data.target);
  const existing = app.vault.getAbstractFileByPath(path);
  if (data.annotations.length === 0) {
    if (existing instanceof import_obsidian3.TFile)
      await app.fileManager.trashFile(existing);
    return;
  }
  const body = JSON.stringify(data, null, 2);
  if (existing instanceof import_obsidian3.TFile)
    await app.vault.modify(existing, body);
  else
    await app.vault.create(path, body);
}

// src/store/review.ts
var BUCKET_ORDER = ["today", "week", "month", "older"];
var DAY = 864e5;
function bucketize(entries, now) {
  const out = { today: [], week: [], month: [], older: [] };
  for (const e of entries) {
    const age = now - Date.parse(lastMarked(e.annotation));
    if (age < DAY)
      out.today.push(e);
    else if (age < 7 * DAY)
      out.week.push(e);
    else if (age < 30 * DAY)
      out.month.push(e);
    else
      out.older.push(e);
  }
  return out;
}
function pickResurface(entries, n, rand) {
  const decorated = entries.map((entry) => ({ entry, jitter: rand() }));
  decorated.sort((a, b) => {
    const seen = a.entry.annotation.reviewed.length - b.entry.annotation.reviewed.length;
    if (seen !== 0)
      return seen;
    return a.jitter - b.jitter;
  });
  return decorated.slice(0, Math.max(0, n)).map((d) => d.entry);
}
function byNewest(a, b) {
  return lastMarked(b.annotation).localeCompare(lastMarked(a.annotation));
}

// src/store/attentionIndex.ts
var AttentionIndex = class {
  constructor(app) {
    this.app = app;
    this.entries = [];
  }
  /** Rescan every sidecar in the vault. Cheap enough to run on load. */
  async rebuild() {
    const next = [];
    for (const file of this.app.vault.getFiles()) {
      if (!isSidecarPath(file.path))
        continue;
      const targetPath = targetPathFor(file.path);
      if (!targetPath)
        continue;
      const data = await loadSidecar(this.app, targetPath);
      for (const annotation of data.annotations) {
        next.push({ targetPath, annotation });
      }
    }
    next.sort(byNewest);
    this.entries = next;
  }
  /** Replace one file's entries in place (after an edit, without a full scan). */
  replaceFile(targetPath, annotations) {
    this.entries = this.entries.filter((e) => e.targetPath !== targetPath);
    for (const annotation of annotations)
      this.entries.push({ targetPath, annotation });
    this.entries.sort(byNewest);
  }
  /** Follow a rename so the index doesn't point at a path that's gone. */
  renameFile(oldPath, newPath) {
    for (const e of this.entries) {
      if (e.targetPath === oldPath)
        e.targetPath = newPath;
    }
  }
  all() {
    return this.entries;
  }
  buckets(now = Date.now()) {
    return bucketize(this.entries, now);
  }
  resurface(n, rand) {
    return pickResurface(this.entries, n, rand);
  }
};

// src/views/ReviewView.ts
var import_obsidian6 = require("obsidian");

// src/store/sorting.ts
var SORT_LABELS = {
  recent: "Recently marked",
  marks: "Times marked",
  oldest: "First marked",
  document: "Document order"
};
function sortsFor(lens) {
  return lens === "file" ? ["document", "recent", "marks", "oldest"] : ["recent", "marks", "oldest"];
}
function resolveSort(sort, lens) {
  return sortsFor(lens).includes(sort) ? sort : "recent";
}
function sortAnnotations(items, sort) {
  const out = [...items];
  switch (sort) {
    case "recent":
      return out.sort((a, b) => lastMarked(b.annotation).localeCompare(lastMarked(a.annotation)));
    case "oldest":
      return out.sort((a, b) => firstMarked(a.annotation).localeCompare(firstMarked(b.annotation)));
    case "marks":
      return out.sort((a, b) => b.annotation.hits.length - a.annotation.hits.length || lastMarked(b.annotation).localeCompare(lastMarked(a.annotation)));
    default:
      return out;
  }
}

// src/anchor/textQuote.ts
var CONTEXT_LEN = 32;
function describe(text, from, to) {
  return {
    quote: text.slice(from, to),
    prefix: text.slice(Math.max(0, from - CONTEXT_LEN), from),
    suffix: text.slice(to, to + CONTEXT_LEN),
    from,
    to
  };
}
function commonSuffixLen(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[a.length - 1 - n] === b[b.length - 1 - n])
    n++;
  return n;
}
function commonPrefixLen(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[n] === b[n])
    n++;
  return n;
}
function allOccurrences(text, needle) {
  if (needle.length === 0)
    return [];
  const out = [];
  let at = text.indexOf(needle);
  while (at >= 0) {
    out.push(at);
    at = text.indexOf(needle, at + 1);
  }
  return out;
}
function resolve(text, anchor) {
  const { quote } = anchor;
  if (quote.length === 0)
    return null;
  if (text.slice(anchor.from, anchor.to) === quote) {
    return { from: anchor.from, to: anchor.to, how: "exact" };
  }
  const hits = allOccurrences(text, quote);
  if (hits.length === 0)
    return null;
  if (hits.length === 1) {
    return { from: hits[0], to: hits[0] + quote.length, how: "unique" };
  }
  let best = -1;
  let bestScore = -1;
  for (const at of hits) {
    const score = commonSuffixLen(text.slice(0, at), anchor.prefix) + commonPrefixLen(text.slice(at + quote.length), anchor.suffix);
    if (score > bestScore) {
      bestScore = score;
      best = at;
    }
  }
  if (bestScore > 0) {
    return { from: best, to: best + quote.length, how: "context" };
  }
  let nearest = hits[0];
  for (const at of hits) {
    if (Math.abs(at - anchor.from) < Math.abs(nearest - anchor.from))
      nearest = at;
  }
  return { from: nearest, to: nearest + quote.length, how: "nearest" };
}
function nthOccurrence(text, needle, n) {
  if (needle.length === 0 || n < 0)
    return -1;
  let at = text.indexOf(needle);
  for (let i = 0; i < n && at >= 0; i++)
    at = text.indexOf(needle, at + 1);
  return at;
}
function countOccurrences(before, needle) {
  if (needle.length === 0)
    return 0;
  let n = 0;
  let at = before.indexOf(needle);
  while (at >= 0) {
    n++;
    at = before.indexOf(needle, at + 1);
  }
  return n;
}

// src/anchor/plainText.ts
var WRAPPERS = ["***", "___", "**", "__", "~~", "==", "*", "_", "`"];
function project(source) {
  let text = "";
  const map = [];
  let i = 0;
  const take = (n) => {
    for (let k = 0; k < n; k++) {
      text += source[i];
      map.push(i);
      i++;
    }
  };
  while (i < source.length) {
    if (source.startsWith("![", i)) {
      const close = matchLink(source, i + 1);
      if (close) {
        i = close.end;
        continue;
      }
    }
    if (source[i] === "[") {
      const link = matchLink(source, i);
      if (link) {
        i++;
        take(link.labelEnd - i);
        i = link.end;
        continue;
      }
    }
    const wrapper = WRAPPERS.find((w) => source.startsWith(w, i));
    if (wrapper) {
      i += wrapper.length;
      continue;
    }
    take(1);
  }
  return { text, map };
}
function strip(source) {
  return project(source).text;
}
function toSource(p, from, to) {
  if (from < 0 || to > p.text.length || to <= from)
    return null;
  return { from: p.map[from], to: p.map[to - 1] + 1 };
}
function matchLink(source, i) {
  if (source[i] !== "[")
    return null;
  let depth = 0;
  for (let k = i; k < source.length; k++) {
    if (source[k] === "[")
      depth++;
    else if (source[k] === "]") {
      depth--;
      if (depth === 0) {
        if (source[k + 1] !== "(")
          return null;
        const close = source.indexOf(")", k + 2);
        if (close < 0)
          return null;
        return { labelEnd: k, end: close + 1 };
      }
    } else if (source[k] === "\n" && depth > 0) {
      return null;
    }
  }
  return null;
}

// src/anchor/imageAnchor.ts
var EMBED = /!\[\[([^\]]+?)\]\]|!\[([^\]]*)\]\(([^)\s]+)[^)]*\)/g;
var IMAGE_FILE = /\.(png|jpe?g|gif|webp|svg|bmp|avif|ico)(?:[?#]|$)/i;
function findImageEmbeds(source) {
  var _a, _b;
  const out = [];
  EMBED.lastIndex = 0;
  for (let m = EMBED.exec(source); m; m = EMBED.exec(source)) {
    const isWiki = m[1] !== void 0;
    const target = cleanTarget((_b = (_a = m[1]) != null ? _a : m[3]) != null ? _b : "");
    if (isWiki && !IMAGE_FILE.test(target))
      continue;
    out.push({ text: m[0], from: m.index, to: m.index + m[0].length, target });
  }
  return out;
}
function cleanTarget(raw) {
  const withoutOptions = raw.split("|")[0].trim();
  try {
    return decodeURIComponent(withoutOptions);
  } catch (e) {
    return withoutOptions;
  }
}
function embedBySurroundings(source, embeds, before, after, offsetOfPlain, plainText) {
  if (embeds.length === 0)
    return null;
  if (embeds.length === 1)
    return embeds[0];
  const trimmedAfter = after.trim();
  if (trimmedAfter.length >= 2) {
    const at = plainText.indexOf(trimmedAfter);
    if (at >= 0) {
      const cut = offsetOfPlain(at);
      const before_ = embeds.filter((e) => e.to <= cut);
      if (before_.length > 0)
        return before_[before_.length - 1];
    }
  }
  const trimmedBefore = before.trim();
  if (trimmedBefore.length >= 2) {
    const at = plainText.lastIndexOf(trimmedBefore);
    if (at >= 0) {
      const cut = offsetOfPlain(Math.min(at + trimmedBefore.length, plainText.length - 1));
      const after_ = embeds.filter((e) => e.from >= cut);
      if (after_.length > 0)
        return after_[0];
    }
  }
  return null;
}
function imageTargetOf(quote) {
  const found = findImageEmbeds(quote);
  return found.length === 1 && found[0].text === quote.trim() ? found[0].target : null;
}
function isImageQuote(quote) {
  return imageTargetOf(quote) !== null;
}
function imageMatches(src, target) {
  var _a;
  if (!src || !target)
    return false;
  const decoded = safeDecode(src);
  if (decoded.includes(target))
    return true;
  const name = (_a = target.split("/").pop()) != null ? _a : target;
  return name.length > 0 && decoded.includes(name);
}
function srcHint(src) {
  var _a;
  const withoutQuery = safeDecode(src).split(/[?#]/)[0];
  const tail = (_a = withoutQuery.split("/").filter(Boolean).pop()) != null ? _a : "";
  return tail.length >= 4 ? tail : "";
}
function safeDecode(url) {
  try {
    return decodeURIComponent(url);
  } catch (e) {
    return url;
  }
}

// src/anchor/resolveAnchor.ts
function resolveMarkdown(text, anchor) {
  const direct = resolve(text, anchor);
  if (direct)
    return direct;
  if (!isImageQuote(anchor.quote))
    return null;
  const embeds = findImageEmbeds(text);
  if (embeds.length === 0)
    return null;
  const plain = project(text);
  const found = embedBySurroundings(
    text,
    embeds,
    anchor.prefix,
    anchor.suffix,
    (i) => {
      var _a;
      return (_a = plain.map[i]) != null ? _a : 0;
    },
    plain.text
  );
  if (!found)
    return null;
  return { from: found.from, to: found.to, how: "context" };
}

// src/store/documentOrder.ts
async function inDocumentOrder(app, file, annotations, text) {
  if (annotations.length === 0)
    return [];
  let source = text;
  if (source === void 0) {
    try {
      source = await app.vault.cachedRead(file);
    } catch (e) {
      return [...annotations];
    }
  }
  const positioned = annotations.map((a) => {
    var _a, _b;
    return {
      a,
      at: a.anchor.kind === "markdown" ? (_b = (_a = resolveMarkdown(source, a.anchor)) == null ? void 0 : _a.from) != null ? _b : null : null
    };
  });
  return positioned.sort((x, y) => {
    if (x.at === null && y.at === null)
      return 0;
    if (x.at === null)
      return 1;
    if (y.at === null)
      return -1;
    return x.at - y.at;
  }).map((p) => p.a);
}

// src/store/orphans.ts
function classify(annotations, text) {
  const live = [];
  const lost = [];
  for (const a of annotations) {
    if (a.anchor.kind !== "markdown") {
      live.push(a);
      continue;
    }
    (resolveMarkdown(text, a.anchor) ? live : lost).push(a);
  }
  return { live, lost };
}

// src/views/ReviewView.ts
var import_obsidian7 = require("obsidian");

// src/hosts/markdown/reveal.ts
var import_obsidian4 = require("obsidian");
async function reveal(app, file, annotation) {
  if (annotation.anchor.kind === "transcript") {
    await revealInTranscript(app, file, annotation);
    return;
  }
  await revealInMarkdown(app, file, annotation);
}
async function revealInTranscript(app, file, annotation) {
  if (annotation.anchor.kind !== "transcript")
    return;
  const at = annotation.anchor.start;
  await app.workspace.getLeaf(false).openFile(file);
  for (let i = 0; i < 40; i++) {
    const media = document.querySelector(".mt-view video, .mt-view audio");
    if (media instanceof HTMLMediaElement) {
      const seek = () => {
        media.currentTime = at;
      };
      if (media.readyState > 0)
        seek();
      else
        media.addEventListener("loadedmetadata", seek, { once: true });
      void media.play();
      const painted = document.querySelector(`.at-hl[data-at-id="${annotation.id}"]`);
      if (painted instanceof HTMLElement) {
        painted.scrollIntoView({ behavior: "smooth", block: "center" });
        flash(painted);
      }
      return;
    }
    await new Promise((r) => window.setTimeout(r, 50));
  }
}
async function revealInMarkdown(app, file, annotation) {
  const leaf = app.workspace.getLeaf(false);
  await leaf.openFile(file);
  const view = leaf.view;
  if (!(view instanceof import_obsidian4.MarkdownView))
    return;
  if (view.getMode() === "source") {
    if (annotation.anchor.kind !== "markdown")
      return;
    const editor = view.editor;
    const at = resolveMarkdown(editor.getValue(), annotation.anchor);
    if (!at)
      return;
    const from = editor.offsetToPos(at.from);
    const to = editor.offsetToPos(at.to);
    editor.setSelection(from, to);
    editor.scrollIntoView({ from, to }, true);
    return;
  }
  await flashWhenPainted(view, annotation.id);
}
async function flashWhenPainted(view, id, tries = 20) {
  for (let i = 0; i < tries; i++) {
    const el = view.contentEl.querySelector(`.at-hl[data-at-id="${id}"]`);
    if (el instanceof HTMLElement) {
      el.scrollIntoView({ behavior: "smooth", block: "center" });
      flash(el);
      return;
    }
    await new Promise((r) => window.setTimeout(r, 50));
  }
}
function flash(el) {
  el.addClass("at-flash");
  window.setTimeout(() => el.removeClass("at-flash"), 1300);
}

// src/ui/CommentModal.ts
var import_obsidian5 = require("obsidian");
var CommentModal = class extends import_obsidian5.Modal {
  constructor(app, quote, initial, onSubmit) {
    super(app);
    this.quote = quote;
    this.onSubmit = onSubmit;
    this.value = initial;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("at-comment-modal");
    contentEl.createDiv("at-comment-quote").setText(this.quote);
    const input = contentEl.createEl("textarea", { cls: "at-comment-input" });
    input.value = this.value;
    input.placeholder = "What caught your attention?";
    input.addEventListener("input", () => {
      this.value = input.value;
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        this.submit();
      }
    });
    new import_obsidian5.Setting(contentEl).addButton(
      (b) => b.setButtonText("Save").setCta().onClick(() => this.submit())
    );
    window.setTimeout(() => input.focus(), 0);
  }
  submit() {
    this.onSubmit(this.value.trim());
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/views/ReviewView.ts
var VIEW_TYPE_REVIEW = "attention-review";
var BUCKET_LABELS = {
  today: "Today",
  week: "This week",
  month: "This month",
  older: "Earlier"
};
var ReviewView = class extends import_obsidian6.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.lens = "file";
    this.sort = "document";
    /**
     * Bumped on every render. Rendering empties the panel, then awaits a file
     * read before appending; two overlapping calls would each empty and then each
     * append, listing everything twice. A render whose generation has been
     * superseded stops instead of drawing.
     */
    this.generation = 0;
    this.resurfaced = null;
  }
  getViewType() {
    return VIEW_TYPE_REVIEW;
  }
  getDisplayText() {
    return "Attention";
  }
  getIcon() {
    return "highlighter";
  }
  async onOpen() {
    this.registerEvent(this.app.workspace.on("file-open", () => {
      void this.render();
    }));
    await this.render();
  }
  async render() {
    const seq = ++this.generation;
    const root = this.contentEl;
    root.empty();
    root.addClass("at-review");
    this.renderHeader(root);
    if (this.resurfaced) {
      for (const e of this.resurfaced)
        this.renderEntry(root, e.annotation, e.targetPath);
      return;
    }
    if (this.lens === "file")
      await this.renderFile(root, seq);
    else
      this.renderAll(root);
  }
  renderHeader(root) {
    const header = root.createDiv("at-review-header");
    const tabs = header.createDiv("at-tabs");
    const tab = (label, lens) => {
      const el = tabs.createEl("button", { text: label, cls: "at-tab" });
      if (this.lens === lens && !this.resurfaced)
        el.addClass("is-active");
      el.addEventListener("click", () => {
        this.lens = lens;
        this.sort = resolveSort(this.sort, lens);
        this.resurfaced = null;
        void this.render();
      });
    };
    tab("This note", "file");
    tab("All", "all");
    const resurface = header.createEl("button", { text: "Resurface", cls: "at-btn" });
    if (this.resurfaced)
      resurface.addClass("is-active");
    resurface.addEventListener("click", () => {
      this.resurfaced = this.resurfaced ? null : this.plugin.index.resurface(this.plugin.settings.resurfaceCount, () => Math.random());
      void this.render();
    });
    if (!this.resurfaced)
      this.renderSortControl(root);
  }
  renderSortControl(root) {
    const bar = root.createDiv("at-sortbar");
    const select = bar.createEl("select", { cls: "at-sort dropdown" });
    for (const s of sortsFor(this.lens)) {
      select.createEl("option", { text: SORT_LABELS[s], attr: { value: s } });
    }
    select.value = this.sort;
    select.addEventListener("change", () => {
      this.sort = select.value;
      void this.render();
    });
  }
  // ── This note ──────────────────────────────────────────────────────────────
  async renderFile(root, seq) {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      this.empty(root, "No note open.");
      return;
    }
    const data = await this.plugin.store.get(file.path);
    if (seq !== this.generation)
      return;
    if (data.annotations.length === 0) {
      this.empty(root, `Nothing marked in \u201C${file.basename}\u201D.`);
      return;
    }
    const text = await this.currentText(file);
    if (seq !== this.generation)
      return;
    const { live, lost } = classify(data.annotations, text);
    const ordered = this.sort === "document" ? await inDocumentOrder(this.app, file, live, text) : sortAnnotations(live.map((annotation) => ({ annotation })), this.sort).map((x) => x.annotation);
    if (seq !== this.generation)
      return;
    if (ordered.length > 0) {
      root.createDiv("at-bucket-title").setText(`${ordered.length} in this note`);
      for (const a of ordered)
        this.renderEntry(root, a, file.path);
    }
    if (lost.length > 0) {
      root.createDiv("at-bucket-title at-lost-title").setText(`${lost.length} lost \u2014 the text they marked is gone`);
      for (const a of lost)
        this.renderEntry(root, a, file.path, true);
    }
    if (ordered.length === 0 && lost.length === 0) {
      this.empty(root, `Nothing marked in \u201C${file.basename}\u201D.`);
    }
  }
  // ── All ────────────────────────────────────────────────────────────────────
  renderAll(root) {
    const all = this.plugin.index.all();
    if (all.length === 0) {
      this.empty(root, "Nothing marked yet. Select text in a note to mark it.");
      return;
    }
    if (this.sort !== "recent") {
      const sorted = sortAnnotations(all, this.sort);
      root.createDiv("at-bucket-title").setText(`${sorted.length} marked`);
      for (const e of sorted)
        this.renderEntry(root, e.annotation, e.targetPath);
      return;
    }
    const buckets = this.plugin.index.buckets();
    for (const key of BUCKET_ORDER) {
      const entries = buckets[key];
      if (entries.length === 0)
        continue;
      root.createDiv("at-bucket-title").setText(`${BUCKET_LABELS[key]} \xB7 ${entries.length}`);
      for (const e of entries)
        this.renderEntry(root, e.annotation, e.targetPath);
    }
  }
  // ── Shared ─────────────────────────────────────────────────────────────────
  /** What the file says right now — from the editor if it's open, else disk. */
  async currentText(file) {
    var _a;
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const view = leaf.view;
      if (view instanceof import_obsidian7.MarkdownView && ((_a = view.file) == null ? void 0 : _a.path) === file.path) {
        return view.editor.getValue();
      }
    }
    try {
      return await this.app.vault.cachedRead(file);
    } catch (e) {
      return "";
    }
  }
  empty(root, message) {
    root.createDiv("at-empty").setText(message);
  }
  renderEntry(root, annotation, targetPath, lost = false) {
    var _a, _b;
    const el = root.createDiv("at-entry");
    if (lost)
      el.addClass("at-entry-lost");
    if (isImageQuote(annotation.anchor.quote)) {
      const thumb = el.createDiv("at-thumb");
      void import_obsidian6.MarkdownRenderer.render(this.app, annotation.anchor.quote, thumb, targetPath, this);
    } else {
      el.createDiv("at-quote").setText(annotation.anchor.quote);
    }
    if (isComment(annotation)) {
      el.createDiv("at-body").setText((_a = annotation.body) != null ? _a : "");
    }
    const meta = el.createDiv("at-meta");
    const left = meta.createDiv("at-meta-left");
    if (this.lens === "all" || this.resurfaced) {
      const name = (_b = targetPath.split("/").pop()) != null ? _b : targetPath;
      left.createSpan({ text: name.replace(/\.md$/, ""), cls: "at-source" });
    }
    if (annotation.anchor.kind === "transcript") {
      left.createSpan({ text: fmtTime(annotation.anchor.start), cls: "at-time" });
    }
    const right = meta.createDiv("at-meta-right");
    if (annotation.hits.length > 1) {
      right.createSpan({ text: `${annotation.hits.length}\xD7`, cls: "at-hits" });
    }
    right.createSpan({
      text: formatWhen(lastMarked(annotation), this.plugin.settings.timeFormat),
      cls: "at-when"
    });
    const actions = el.createDiv("at-entry-actions");
    const act = (label, title, fn, warn = false) => {
      const b = actions.createEl("button", { cls: "at-icon-btn", text: label });
      b.setAttribute("aria-label", title);
      b.setAttribute("title", title);
      if (warn)
        b.addClass("mod-warning");
      b.addEventListener("click", (e) => {
        e.stopPropagation();
        fn();
      });
    };
    if (lost) {
      act(
        "\u26B2",
        "Re-attach: select the text in the note first",
        () => {
          void this.reattach(targetPath, annotation);
        }
      );
    } else {
      act(
        "\uFF0B",
        "Mark again \u2014 it caught you once more",
        () => {
          void this.markAgain(targetPath, annotation);
        }
      );
    }
    act(
      "\u{1F4AC}",
      isComment(annotation) ? "Edit comment" : "Add a comment",
      () => this.editComment(targetPath, annotation)
    );
    act(
      "\u2715",
      "Remove this mark",
      () => {
        void this.plugin.store.remove(targetPath, annotation.id);
      },
      true
    );
    if (!lost)
      el.addEventListener("click", () => {
        void this.jumpTo(annotation, targetPath);
      });
    el.addEventListener("contextmenu", (e) => this.entryMenu(e, annotation, targetPath));
  }
  entryMenu(e, annotation, targetPath) {
    e.preventDefault();
    const menu = new import_obsidian6.Menu();
    menu.addItem((i) => i.setTitle("Go to").setIcon("arrow-right").onClick(() => {
      void this.jumpTo(annotation, targetPath);
    }));
    menu.addItem((i) => i.setTitle("Mark again").setIcon("plus").onClick(() => {
      void this.markAgain(targetPath, annotation);
    }));
    menu.addItem((i) => i.setTitle(isComment(annotation) ? "Edit comment\u2026" : "Add a comment\u2026").setIcon("message-square").onClick(() => this.editComment(targetPath, annotation)));
    menu.addItem((i) => i.setTitle("Re-attach to selection").setIcon("link").onClick(() => {
      void this.reattach(targetPath, annotation);
    }));
    menu.addItem((i) => i.setTitle("Copy text").setIcon("copy").onClick(() => {
      void navigator.clipboard.writeText(annotation.anchor.quote);
    }));
    menu.addItem((i) => i.setTitle("Remove mark").setIcon("trash").setWarning(true).onClick(() => {
      void this.plugin.store.remove(targetPath, annotation.id);
    }));
    menu.showAtMouseEvent(e);
  }
  /**
   * Point a lost mark at whatever is selected in the note now.
   *
   * The mark keeps its identity — its comment, and every time it caught you —
   * and only learns where it lives. Re-marking the passage by hand would give
   * you a new mark and quietly lose that history.
   */
  async reattach(targetPath, annotation) {
    var _a;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
    if (!view || ((_a = view.file) == null ? void 0 : _a.path) !== targetPath || view.getMode() !== "source") {
      new import_obsidian6.Notice("Open the note in editing mode and select the text this should mark.");
      return;
    }
    const editor = view.editor;
    const from = editor.posToOffset(editor.getCursor("from"));
    const to = editor.posToOffset(editor.getCursor("to"));
    if (from === to) {
      new import_obsidian6.Notice("Select the text this mark should attach to, then try again.");
      return;
    }
    await this.plugin.store.update(targetPath, annotation.id, {
      anchor: { kind: "markdown", ...describe(editor.getValue(), from, to) }
    });
    new import_obsidian6.Notice(`Re-attached to \u201C${editor.getValue().slice(from, to).slice(0, 20)}\u201D.`);
  }
  async markAgain(targetPath, annotation) {
    const updated = await this.plugin.store.markAgain(targetPath, annotation.id);
    if (updated)
      new import_obsidian6.Notice(`Marked ${updated.hits.length}\xD7 now`);
  }
  editComment(targetPath, annotation) {
    var _a;
    new CommentModal(this.app, annotation.anchor.quote, (_a = annotation.body) != null ? _a : "", (body) => {
      void this.plugin.store.update(targetPath, annotation.id, { body: body || null });
    }).open();
  }
  async jumpTo(annotation, targetPath) {
    const file = this.app.vault.getAbstractFileByPath(targetPath);
    if (!(file instanceof import_obsidian6.TFile))
      return;
    await reveal(this.app, file, annotation);
    await this.plugin.markReviewed({ targetPath, annotation });
  }
};
function fmtTime(seconds) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

// src/store/annotationStore.ts
var AnnotationStore = class {
  constructor(app, index) {
    this.app = app;
    this.index = index;
    this.cache = /* @__PURE__ */ new Map();
    this.listeners = [];
    /** Paths with a warm already in flight, so a miss can't spawn a stampede. */
    this.warming = /* @__PURE__ */ new Set();
  }
  /** Annotations for a file, from cache when we have it. */
  async get(targetPath) {
    const cached = this.cache.get(targetPath);
    if (cached)
      return cached;
    const loaded = await loadSidecar(this.app, targetPath);
    this.cache.set(targetPath, loaded);
    return loaded;
  }
  /**
   * Synchronous read for render paths that can't await.
   *
   * A miss means a view is painting a file nobody has loaded yet — which used
   * to render as "this file has no annotations" and stay that way. So a miss
   * kicks off a load and notifies when it lands, turning a silent wrong answer
   * into a brief empty one.
   */
  peek(targetPath) {
    const cached = this.cache.get(targetPath);
    if (cached)
      return cached.annotations;
    if (!this.warming.has(targetPath)) {
      this.warming.add(targetPath);
      void this.get(targetPath).then(() => this.emit(targetPath)).finally(() => this.warming.delete(targetPath));
    }
    return [];
  }
  /** Load into the cache so a later peek() has something to paint. */
  async warm(targetPath) {
    await this.get(targetPath);
    this.emit(targetPath);
  }
  /**
   * Record that a passage caught you.
   *
   * Marking something already marked appends to its history instead of making a
   * second annotation. A line that moves you three times over a year is the
   * strongest thing this plugin can know about you, and deduplicating it away
   * would throw exactly that away.
   *
   * Returns the annotation and whether this was a fresh mark or a repeat, so
   * the caller can say so.
   */
  async mark(targetPath, anchor, body) {
    const data = await this.get(targetPath);
    const now = new Date().toISOString();
    const existing = data.annotations.find((a) => sameSpot(a.anchor, anchor));
    if (existing) {
      existing.hits.push(now);
      if (body)
        existing.body = existing.body ? `${existing.body}

${body}` : body;
      existing.updated = now;
      await this.commit(targetPath, data);
      return { annotation: existing, repeat: true };
    }
    const annotation = {
      id: newId(),
      anchor,
      hits: [now],
      body,
      reviewed: []
    };
    data.annotations.push(annotation);
    await this.commit(targetPath, data);
    return { annotation, repeat: false };
  }
  /**
   * Record another hit on an annotation you already have in hand.
   *
   * Same effect as marking the passage again, but addressed by id — the review
   * panel is looking at the annotation, not at the text, and shouldn't have to
   * reconstruct an anchor to say "this still matters".
   */
  async markAgain(targetPath, id) {
    const data = await this.get(targetPath);
    const target = data.annotations.find((a) => a.id === id);
    if (!target)
      return null;
    const now = new Date().toISOString();
    target.hits.push(now);
    target.updated = now;
    await this.commit(targetPath, data);
    return target;
  }
  async add(targetPath, annotation) {
    const data = await this.get(targetPath);
    data.annotations.push(annotation);
    await this.commit(targetPath, data);
  }
  async update(targetPath, id, patch) {
    const data = await this.get(targetPath);
    const target = data.annotations.find((a) => a.id === id);
    if (!target)
      return;
    Object.assign(target, patch, { updated: new Date().toISOString() });
    await this.commit(targetPath, data);
  }
  async remove(targetPath, id) {
    const data = await this.get(targetPath);
    const before = data.annotations.length;
    data.annotations = data.annotations.filter((a) => a.id !== id);
    if (data.annotations.length === before)
      return;
    await this.commit(targetPath, data);
  }
  /** Drop a cache entry (after an external edit or a rename). */
  forget(targetPath) {
    this.cache.delete(targetPath);
  }
  async commit(targetPath, data) {
    await saveSidecar(this.app, data);
    this.cache.set(targetPath, data);
    this.index.replaceFile(targetPath, data.annotations);
    this.emit(targetPath);
  }
  onChange(listener) {
    this.listeners.push(listener);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== listener);
    };
  }
  emit(targetPath) {
    for (const l of this.listeners)
      l(targetPath);
  }
};

// src/hosts/markdown/MarkdownHost.ts
var import_obsidian8 = require("obsidian");

// src/ui/SelectionPopover.ts
var SelectionPopover = class {
  constructor() {
    this.el = null;
    this.dismiss = () => this.hide();
  }
  showAt(rect, actions) {
    this.hide();
    const el = document.createElement("div");
    el.className = "at-popover";
    const add = (label, title, fn, cls = "at-pop-btn") => {
      const b = el.createEl("button", { cls, text: label });
      b.setAttribute("aria-label", title);
      b.setAttribute("title", title);
      b.addEventListener("mousedown", (e) => {
        e.preventDefault();
        fn();
        this.hide();
      });
    };
    if (actions.onMark)
      add("Mark", "Mark this", actions.onMark, "at-pop-btn at-pop-mark");
    if (actions.onMarkAgain)
      add("\uFF0B", "Mark again \u2014 it caught you once more", actions.onMarkAgain);
    add("\u{1F4AC}", "Add or edit a comment", actions.onComment);
    if (actions.onRemove)
      add("\u2715", "Remove mark", actions.onRemove);
    if (actions.onZoom)
      add("\u{1F50D}", "Open the picture", actions.onZoom);
    document.body.appendChild(el);
    this.el = el;
    const { width, height } = el.getBoundingClientRect();
    const left = Math.min(
      Math.max(8, rect.left + rect.width / 2 - width / 2),
      window.innerWidth - width - 8
    );
    const above = rect.top - height - 8;
    el.style.left = `${left}px`;
    el.style.top = `${above < 8 ? rect.bottom + 8 : above}px`;
    window.setTimeout(() => {
      document.addEventListener("mousedown", this.dismiss);
      document.addEventListener("keydown", this.dismiss);
    }, 0);
  }
  hide() {
    var _a;
    document.removeEventListener("mousedown", this.dismiss);
    document.removeEventListener("keydown", this.dismiss);
    (_a = this.el) == null ? void 0 : _a.remove();
    this.el = null;
  }
};

// src/ui/CommentBubble.ts
var CommentBubble = class {
  constructor(timeFormat = "") {
    this.timeFormat = timeFormat;
    this.el = null;
    this.dismiss = (e) => {
      var _a;
      if (e.target instanceof Node && ((_a = this.el) == null ? void 0 : _a.contains(e.target)))
        return;
      this.hide();
    };
  }
  showFor(rect, annotation, actions) {
    this.hide();
    const el = document.createElement("div");
    el.className = "at-bubble";
    const body = annotation.body;
    if (body && body.trim().length > 0)
      el.createDiv("at-bubble-body").setText(body);
    else
      el.createDiv("at-bubble-empty").setText("No comment yet.");
    const hits = annotation.hits;
    const times = el.createDiv("at-bubble-hits");
    times.createSpan({ cls: "at-hit-count", text: hits.length === 1 ? "Marked once" : `Marked ${hits.length}\xD7` });
    for (const at of [...hits].reverse()) {
      times.createDiv("at-hit-time").setText(formatWhen(at, this.timeFormat));
    }
    const row = el.createDiv("at-bubble-actions");
    const add = (label, fn, warn = false) => {
      const b = row.createEl("button", { cls: "at-pop-btn", text: label });
      if (warn)
        b.addClass("mod-warning");
      b.addEventListener("click", () => {
        fn();
        this.hide();
      });
    };
    add(body ? "Edit" : "Comment", actions.onEdit);
    add("Mark again", actions.onMarkAgain);
    add("Remove", actions.onRemove, true);
    document.body.appendChild(el);
    this.el = el;
    const { width, height } = el.getBoundingClientRect();
    const left = Math.min(
      Math.max(8, rect.left + rect.width / 2 - width / 2),
      window.innerWidth - width - 8
    );
    const above = rect.top - height - 8;
    el.style.left = `${left}px`;
    el.style.top = `${above < 8 ? rect.bottom + 8 : above}px`;
    window.setTimeout(() => {
      document.addEventListener("mousedown", this.dismiss);
      document.addEventListener("keydown", this.dismiss);
    }, 0);
  }
  hide() {
    var _a;
    document.removeEventListener("mousedown", this.dismiss);
    document.removeEventListener("keydown", this.dismiss);
    (_a = this.el) == null ? void 0 : _a.remove();
    this.el = null;
  }
};

// src/hosts/markdown/MarkdownHost.ts
var MarkdownHost = class {
  constructor(app, plugin, store, settings) {
    this.app = app;
    this.plugin = plugin;
    this.store = store;
    this.settings = settings;
    /** The element right-clicked, captured before any menu is built. */
    this.lastTarget = null;
    /** Set while re-issuing a click we intercepted, so we don't catch our own. */
    this.passingThrough = false;
    this.popover = new SelectionPopover();
    this.bubble = new CommentBubble(settings.timeFormat);
  }
  register() {
    this.plugin.registerDomEvent(
      document,
      "contextmenu",
      (e) => {
        this.lastTarget = e.target instanceof HTMLElement ? e.target : null;
      },
      true
    );
    this.plugin.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, info) => {
        this.onEditorMenu(menu, editor, info);
      })
    );
    this.plugin.registerDomEvent(document, "mouseup", (e) => {
      if (e.button !== 0 || !this.settings.popoverOnSelection)
        return;
      if (e.target instanceof HTMLElement && e.target.closest(".at-hl, .at-popover, .at-bubble"))
        return;
      window.setTimeout(() => {
        void this.onSelectionMade();
      }, 0);
    });
    this.plugin.registerDomEvent(document, "click", (e) => {
      var _a, _b;
      if (this.passingThrough)
        return;
      const img = e.target instanceof HTMLElement ? e.target.closest("img") : null;
      if (!(img instanceof HTMLImageElement))
        return;
      const view = this.app.workspace.getActiveViewOfType(import_obsidian8.MarkdownView);
      if (!(view == null ? void 0 : view.file) || !view.contentEl.contains(img))
        return;
      if (((_b = (_a = window.getSelection()) == null ? void 0 : _a.toString().trim().length) != null ? _b : 0) > 0)
        return;
      e.preventDefault();
      e.stopPropagation();
      void this.showImagePopover(view.file, img);
    }, true);
    this.plugin.registerDomEvent(document, "click", (e) => {
      var _a, _b, _c, _d;
      const el = e.target instanceof HTMLElement ? e.target : null;
      const hit = (_a = el == null ? void 0 : el.closest(".at-hl")) != null ? _a : null;
      if (!(hit instanceof HTMLElement))
        return;
      if (((_c = (_b = window.getSelection()) == null ? void 0 : _b.toString().trim().length) != null ? _c : 0) > 0)
        return;
      const file = (_d = this.app.workspace.getActiveViewOfType(import_obsidian8.MarkdownView)) == null ? void 0 : _d.file;
      if (file)
        void this.showBubble(file, hit);
    });
    this.plugin.registerDomEvent(document, "contextmenu", (e) => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian8.MarkdownView);
      if (!(view == null ? void 0 : view.file) || view.getMode() !== "preview")
        return;
      if (!this.hasSomethingToOffer(view))
        return;
      e.preventDefault();
      void this.showReadingMenu(e, view);
    });
  }
  detach() {
    this.popover.hide();
    this.bubble.hide();
  }
  /** The choice a click on a picture now offers, zoom included. */
  async showImagePopover(file, img) {
    const rect = img.getBoundingClientRect();
    const id = img.dataset.atId;
    const zoom = () => {
      this.passingThrough = true;
      img.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true, view: window }));
      window.setTimeout(() => {
        this.passingThrough = false;
      }, 0);
    };
    if (!id) {
      this.popover.showAt(rect, {
        onMark: () => {
          void this.markImage(file, img, null);
        },
        onComment: () => {
          new CommentModal(this.app, "\u{1F5BC} " + (img.getAttribute("alt") || "image"), "", (body) => {
            void this.markImage(file, img, body || null);
          }).open();
        },
        onZoom: zoom
      });
      return;
    }
    this.popover.showAt(rect, {
      onMarkAgain: () => {
        void this.markAgain(file.path, id);
      },
      onComment: () => {
        void this.editComment(file, id);
      },
      onRemove: () => {
        void this.store.remove(file.path, id);
      },
      onZoom: zoom
    });
  }
  async showBubble(file, el) {
    const id = el.dataset.atId;
    if (!id)
      return;
    const data = await this.store.get(file.path);
    const annotation = data.annotations.find((a) => a.id === id);
    if (!annotation)
      return;
    this.bubble.showFor(el.getBoundingClientRect(), annotation, {
      onEdit: () => {
        void this.editComment(file, id);
      },
      onMarkAgain: () => {
        void this.markAgain(file.path, id);
      },
      onRemove: () => {
        void this.store.remove(file.path, id);
      }
    });
  }
  hasSomethingToOffer(view) {
    var _a, _b, _c, _d;
    if ((_a = this.lastTarget) == null ? void 0 : _a.closest(".at-hl"))
      return true;
    if ((_b = this.lastTarget) == null ? void 0 : _b.closest("img"))
      return true;
    const selection = window.getSelection();
    return ((_c = selection == null ? void 0 : selection.toString().trim().length) != null ? _c : 0) > 0 && view.contentEl.contains((_d = selection == null ? void 0 : selection.anchorNode) != null ? _d : null);
  }
  /**
   * Anchor whatever is selected, and say which file it belongs to.
   *
   * Usually the note on screen — but a transcluded note is someone else's
   * text, and a mark on it belongs to that file. Anchoring it to the host
   * would put the mark in a note that doesn't contain the words, where it
   * would never resolve and would vanish the moment the transclusion moved.
   */
  async capture(view) {
    const host = view.file;
    if (!host)
      return null;
    const embedded = this.embeddedFileAt(this.selectionElement(), host);
    if (embedded) {
      const anchor2 = await this.captureInFile(embedded);
      return anchor2 ? { anchor: anchor2, file: embedded } : null;
    }
    if (view.getMode() === "source") {
      const anchor2 = this.captureEditor(view.editor);
      return anchor2 ? { anchor: anchor2, file: host } : null;
    }
    const anchor = await this.captureInFile(host);
    return anchor ? { anchor, file: host } : null;
  }
  /** The markdown view whose content contains `el`. */
  viewContaining(el) {
    if (!el)
      return null;
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const view = leaf.view;
      if (view instanceof import_obsidian8.MarkdownView && view.contentEl.contains(el))
        return view;
    }
    return null;
  }
  /** The element the selection starts in. */
  selectionElement() {
    var _a, _b;
    const node = (_b = (_a = window.getSelection()) == null ? void 0 : _a.anchorNode) != null ? _b : null;
    if (!node)
      return null;
    return node instanceof HTMLElement ? node : node.parentElement;
  }
  /**
   * The note transcluded around `el`, if any.
   *
   * Obsidian renders `![[a note]]` into a container carrying the link it came
   * from, which is enough to resolve the real file.
   */
  embeddedFileAt(el, host) {
    var _a, _b;
    const container = el == null ? void 0 : el.closest(".internal-embed, .markdown-embed");
    if (!(container instanceof HTMLElement))
      return null;
    const link = (_b = (_a = container.getAttribute("src")) != null ? _a : container.getAttribute("data-href")) != null ? _b : "";
    if (!link)
      return null;
    const target = this.app.metadataCache.getFirstLinkpathDest(link.split("#")[0], host.path);
    return target && target.extension === "md" ? target : null;
  }
  captureEditor(editor) {
    const from = editor.posToOffset(editor.getCursor("from"));
    const to = editor.posToOffset(editor.getCursor("to"));
    if (from === to)
      return null;
    return { kind: "markdown", ...describe(editor.getValue(), from, to) };
  }
  /** Selection finished: offer the swatches straight away, if asked to. */
  async onSelectionMade() {
    const selection = window.getSelection();
    if (!selection || selection.toString().trim().length === 0)
      return;
    const view = this.viewContaining(this.selectionElement());
    if (!(view == null ? void 0 : view.file))
      return;
    const rect = selection.getRangeAt(0).getBoundingClientRect();
    const captured = await this.capture(view);
    if (!captured)
      return;
    this.popover.showAt(rect, {
      onMark: () => {
        void this.mark(captured.file, captured.anchor, null);
      },
      onComment: () => this.promptComment(captured.file, captured.anchor, "")
    });
  }
  // ── Editing modes ──────────────────────────────────────────────────────────
  onEditorMenu(menu, editor, info) {
    var _a, _b;
    const file = info.file;
    if (!file)
      return;
    const existing = (_a = this.lastTarget) == null ? void 0 : _a.closest(".at-hl");
    if (existing instanceof HTMLElement) {
      this.addExistingItems(menu, file, existing);
      return;
    }
    const img = (_b = this.lastTarget) == null ? void 0 : _b.closest("img");
    if (img instanceof HTMLImageElement) {
      this.addImageItems(menu, file, img);
      return;
    }
    const anchor = this.captureEditor(editor);
    if (anchor)
      this.addCreateItems(menu, file, anchor);
  }
  // ── Reading mode ───────────────────────────────────────────────────────────
  async showReadingMenu(e, view) {
    var _a, _b;
    const file = view.file;
    if (!file)
      return;
    const menu = new import_obsidian8.Menu();
    const existing = (_a = this.lastTarget) == null ? void 0 : _a.closest(".at-hl");
    const img = (_b = this.lastTarget) == null ? void 0 : _b.closest("img");
    if (existing instanceof HTMLElement) {
      this.addExistingItems(menu, file, existing);
    } else if (img instanceof HTMLImageElement) {
      this.addImageItems(menu, file, img);
    } else {
      const captured = await this.capture(view);
      if (!captured)
        return;
      this.addCreateItems(menu, captured.file, captured.anchor);
    }
    menu.showAtMouseEvent(e);
  }
  /** Locate a rendered selection in a file's source by ordinal. */
  async captureInFile(file) {
    var _a;
    const selection = window.getSelection();
    const selected = (_a = selection == null ? void 0 : selection.toString()) != null ? _a : "";
    if (!selection || selected.trim().length === 0)
      return null;
    const source = await this.app.vault.cachedRead(file);
    const plain = project(source);
    const at = nthOccurrence(plain.text, selected, this.renderedOrdinal(selection, selected));
    if (at < 0) {
      new import_obsidian8.Notice("Attention: could not find that selection in the note.");
      return null;
    }
    const range = toSource(plain, at, at + selected.length);
    if (!range)
      return null;
    return { kind: "markdown", ...describe(source, range.from, range.to) };
  }
  /**
   * How many identical strings precede this selection on screen.
   *
   * Counted within the reading container the selection is actually in, not the
   * whole view: `contentEl` holds the source layer *and* the reading layer at
   * once — only one visible — so counting across it sees the document twice and
   * asks for an occurrence that doesn't exist.
   */
  renderedOrdinal(selection, selected) {
    var _a, _b;
    const sel = selection.getRangeAt(0);
    const node = sel.startContainer;
    const el = node instanceof HTMLElement ? node : node.parentElement;
    const container = (_b = (_a = el == null ? void 0 : el.closest(".markdown-embed-content")) != null ? _a : el == null ? void 0 : el.closest(".markdown-preview-view")) != null ? _b : el == null ? void 0 : el.closest(".cm-content");
    if (!container)
      return 0;
    const before = sel.cloneRange();
    before.selectNodeContents(container);
    before.setEnd(sel.startContainer, sel.startOffset);
    return countOccurrences(before.toString(), selected);
  }
  // ── Menu items ─────────────────────────────────────────────────────────────
  addCreateItems(menu, file, anchor) {
    menu.addItem(
      (item) => item.setTitle("Mark").setIcon("highlighter").onClick(() => {
        void this.mark(file, anchor, null);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Comment\u2026").setIcon("message-square").onClick(() => this.promptComment(file, anchor, ""))
    );
  }
  addExistingItems(menu, file, el) {
    const id = el.dataset.atId;
    if (!id)
      return;
    menu.addItem(
      (item) => item.setTitle("Edit comment\u2026").setIcon("message-square").onClick(() => {
        void this.editComment(file, id);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Remove highlight").setIcon("trash").setWarning(true).onClick(() => {
        void this.store.remove(file.path, id);
      })
    );
  }
  // ── Actions ────────────────────────────────────────────────────────────────
  /** Menu for a rendered image: mark the picture itself. */
  addImageItems(menu, file, img) {
    const id = img.dataset.atId;
    if (id) {
      menu.addItem((i) => i.setTitle("Edit comment\u2026").setIcon("message-square").onClick(() => {
        void this.editComment(file, id);
      }));
      menu.addItem((i) => i.setTitle("Mark again").setIcon("plus").onClick(() => {
        void this.markAgain(file.path, id);
      }));
      menu.addItem((i) => i.setTitle("Remove mark").setIcon("trash").setWarning(true).onClick(() => {
        void this.store.remove(file.path, id);
      }));
      return;
    }
    menu.addItem((i) => i.setTitle("Mark image").setIcon("highlighter").onClick(() => {
      void this.markImage(file, img, null);
    }));
    menu.addItem((i) => i.setTitle("Comment on image\u2026").setIcon("message-square").onClick(() => {
      new CommentModal(this.app, "\u{1F5BC} " + (img.getAttribute("alt") || "image"), "", (body) => {
        void this.markImage(file, img, body || null);
      }).open();
    }));
  }
  /**
   * Anchor a picture by the embed that produced it.
   *
   * Matched on what the image points at rather than by counting images: Live
   * Preview only renders the widgets near the viewport, so a positional count
   * would be wrong exactly when the note is long enough for it to matter. The
   * same picture used twice is told apart by order among its own duplicates.
   */
  async markImage(file, img, body) {
    var _a, _b;
    const source = await this.app.vault.cachedRead(file);
    const embeds = findImageEmbeds(source);
    if (embeds.length === 0) {
      new import_obsidian8.Notice("Attention: could not find that image in the note.");
      return;
    }
    const src = (_a = img.getAttribute("src")) != null ? _a : "";
    const byTarget = embeds.filter((e) => imageMatches(src, e.target));
    let embed = (_b = byTarget[0]) != null ? _b : null;
    if (byTarget.length > 1) {
      const same = Array.from(document.querySelectorAll("img")).filter((other) => other.getAttribute("src") === src);
      embed = byTarget[Math.min(Math.max(same.indexOf(img), 0), byTarget.length - 1)];
    }
    if (!embed) {
      const plain = project(source);
      embed = embedBySurroundings(
        source,
        embeds,
        this.textAround(img, "before"),
        this.textAround(img, "after"),
        (i) => {
          var _a2;
          return (_a2 = plain.map[i]) != null ? _a2 : 0;
        },
        plain.text
      );
    }
    if (!embed) {
      new import_obsidian8.Notice("Attention: could not tell which image in the note that is.");
      return;
    }
    await this.mark(file, {
      kind: "markdown",
      ...describe(source, embed.from, embed.to),
      imageHint: srcHint(src)
    }, body);
  }
  /** A little of the rendered text immediately before or after an image. */
  textAround(img, side) {
    var _a;
    const block = (_a = img.closest("p, li, blockquote, div")) != null ? _a : img.parentElement;
    if (!block)
      return "";
    const range = document.createRange();
    if (side === "after") {
      range.setStartAfter(img);
      range.setEnd(block, block.childNodes.length);
    } else {
      range.setStart(block, 0);
      range.setEndBefore(img);
    }
    const text = range.toString();
    return side === "after" ? text.slice(0, 40) : text.slice(-40);
  }
  promptComment(file, anchor, initial) {
    new CommentModal(this.app, anchor.quote, initial, (body) => {
      void this.mark(file, anchor, body || null);
    }).open();
  }
  async markAgain(targetPath, id) {
    const updated = await this.store.markAgain(targetPath, id);
    if (updated)
      new import_obsidian8.Notice(`Marked ${updated.hits.length}\xD7 now`);
  }
  async editComment(file, id) {
    var _a;
    const data = await this.store.get(file.path);
    const annotation = data.annotations.find((a) => a.id === id);
    if (!annotation)
      return;
    new CommentModal(this.app, annotation.anchor.quote, (_a = annotation.body) != null ? _a : "", (body) => {
      void this.store.update(file.path, id, { body: body || null });
    }).open();
  }
  async mark(file, anchor, body) {
    const { repeat, annotation } = await this.store.mark(file.path, anchor, body);
    if (repeat)
      new import_obsidian8.Notice(`Marked ${annotation.hits.length}\xD7 now`);
  }
};

// src/hosts/markdown/decorations.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_obsidian9 = require("obsidian");

// src/hosts/paintQuote.ts
function paintQuote(root, annotation, quote = annotation.anchor.quote) {
  if (!quote)
    return;
  if (root.closest(".at-review"))
    return;
  const nodes = textNodesIn(root);
  if (nodes.length === 0)
    return;
  const starts = [];
  let full = "";
  for (const n of nodes) {
    starts.push(full.length);
    full += n.data;
  }
  const spans = [];
  for (let at = full.indexOf(quote); at >= 0; at = full.indexOf(quote, at + quote.length)) {
    const end = at + quote.length;
    for (let i = 0; i < nodes.length; i++) {
      const nodeStart = starts[i];
      const nodeEnd = nodeStart + nodes[i].data.length;
      if (nodeEnd <= at || nodeStart >= end)
        continue;
      spans.push({
        node: nodes[i],
        from: Math.max(at, nodeStart) - nodeStart,
        to: Math.min(end, nodeEnd) - nodeStart
      });
    }
  }
  for (const s of spans.reverse())
    wrap(s.node, s.from, s.to, annotation);
}
function textNodesIn(root) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const out = [];
  for (let n = walker.nextNode(); n; n = walker.nextNode()) {
    const text = n;
    if (text.data.length > 0 && !isInsideHighlight(text))
      out.push(text);
  }
  return out;
}
function wrap(node, from, to, annotation) {
  if (to <= from)
    return;
  const tail = from > 0 ? node.splitText(from) : node;
  if (to - from < tail.data.length)
    tail.splitText(to - from);
  const span = document.createElement("span");
  span.className = isComment(annotation) ? "at-hl at-hl-comment" : "at-hl";
  span.dataset.atId = annotation.id;
  tail.replaceWith(span);
  span.appendChild(tail);
}
function isInsideHighlight(node) {
  var _a;
  return ((_a = node.parentElement) == null ? void 0 : _a.closest(".at-hl")) != null;
}

// src/hosts/paintImage.ts
function paintImages(root, annotations) {
  var _a, _b;
  if (root.closest(".at-review"))
    return;
  const targets = [];
  for (const a of annotations) {
    if (a.anchor.kind !== "markdown")
      continue;
    const target = imageTargetOf(a.anchor.quote);
    if (target)
      targets.push({ target, hint: (_a = a.anchor.imageHint) != null ? _a : "", annotation: a });
  }
  if (targets.length === 0)
    return;
  for (const img of Array.from(root.querySelectorAll("img"))) {
    if (!(img instanceof HTMLImageElement))
      continue;
    const src = (_b = img.getAttribute("src")) != null ? _b : "";
    const hint = srcHint(src);
    const hit = targets.find((t) => imageMatches(src, t.target) || t.hint && t.hint === hint);
    if (!hit)
      continue;
    img.addClass("at-img");
    img.toggleClass("at-img-comment", isComment(hit.annotation));
    img.dataset.atId = hit.annotation.id;
    const body = hit.annotation.body;
    img.setAttribute("title", body && body.trim() ? body : "Marked");
  }
}

// src/hosts/markdown/decorations.ts
var refreshAnnotations = import_state.StateEffect.define();
var onEdit = null;
var onDrift = null;
function setEditListener(listener) {
  onEdit = listener;
}
function setDriftListener(listener) {
  onDrift = listener;
}
function build(view, provider) {
  var _a, _b;
  const path = (_b = (_a = view.state.field(import_obsidian9.editorInfoField, false)) == null ? void 0 : _a.file) == null ? void 0 : _b.path;
  if (!path)
    return import_view.Decoration.none;
  const annotations = provider(path);
  if (annotations.length === 0)
    return import_view.Decoration.none;
  const doc = view.state.doc.toString();
  const ranges = [];
  for (const a of annotations) {
    if (a.anchor.kind !== "markdown")
      continue;
    const at = resolveMarkdown(doc, a.anchor);
    if (!at || at.from === at.to)
      continue;
    if (at.how !== "exact")
      onDrift == null ? void 0 : onDrift(path, a.id, a.anchor, doc, at);
    ranges.push(
      import_view.Decoration.mark({
        class: isComment(a) ? "at-hl at-hl-comment" : "at-hl",
        attributes: { "data-at-id": a.id }
      }).range(at.from, at.to)
    );
  }
  return import_view.Decoration.set(ranges, true);
}
function annotationDecorations(provider) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = build(view, provider);
      }
      update(u) {
        const refreshed = u.transactions.some(
          (t) => t.effects.some((e) => e.is(refreshAnnotations))
        );
        if (u.docChanged)
          reportEdit(u);
        if (u.docChanged || u.viewportChanged || refreshed) {
          this.decorations = build(u.view, provider);
        }
      }
    },
    { decorations: (v) => v.decorations }
  );
}
function reportEdit(u) {
  var _a, _b;
  if (!onEdit)
    return;
  const path = (_b = (_a = u.state.field(import_obsidian9.editorInfoField, false)) == null ? void 0 : _a.file) == null ? void 0 : _b.path;
  if (!path)
    return;
  const changes = [];
  u.changes.iterChanges((fromA, toA, fromB, toB) => {
    changes.push({ fromA, toA, fromB, toB });
  });
  if (changes.length > 0)
    onEdit(path, changes, u.state.doc.toString());
}
function repaintEditors(app, provider) {
  app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
    const view = leaf.view;
    if (!(view instanceof import_obsidian9.MarkdownView))
      return;
    const cm = view.editor.cm;
    cm == null ? void 0 : cm.dispatch({ effects: refreshAnnotations.of() });
    if (provider)
      paintRenderedWidgets(view, provider);
  });
}
function paintRenderedWidgets(view, provider) {
  var _a;
  const path = (_a = view.file) == null ? void 0 : _a.path;
  const content = view.contentEl.querySelector(".cm-content");
  if (!path || !(content instanceof HTMLElement))
    return;
  const annotations = provider(path);
  paintImages(content, annotations);
  for (const a of annotations) {
    if (a.anchor.kind !== "markdown")
      continue;
    paintQuote(content, a);
  }
}

// src/anchor/repair.ts
function mapRange(from, to, changes) {
  let a = from;
  let b = to;
  for (const c of changes) {
    const grow = c.toB - c.fromB - (c.toA - c.fromA);
    if (c.toA <= a) {
      a += grow;
      b += grow;
      continue;
    }
    if (c.fromA >= b)
      continue;
    if (c.fromA <= a && c.toA >= b)
      return null;
    a = a <= c.fromA ? a : Math.max(c.fromB, Math.min(a + grow, c.toB));
    b = b >= c.toA ? b + grow : Math.max(c.fromB, Math.min(b + grow, c.toB));
    if (b <= a)
      return null;
  }
  return b > a ? { from: a, to: b } : null;
}
function reanchor(anchor, text, at) {
  return { kind: "markdown", ...describe(text, at.from, at.to) };
}
function anchorsDiffer(a, b) {
  return a.from !== b.from || a.to !== b.to || a.quote !== b.quote || a.prefix !== b.prefix || a.suffix !== b.suffix;
}

// src/anchor/AnchorTracker.ts
var SETTLE_MS = 800;
var AnchorTracker = class {
  constructor(store) {
    this.store = store;
    this.pending = /* @__PURE__ */ new Map();
  }
  /** A note changed in the editor. */
  onEdit(path, changes, text) {
    if (changes.length === 0)
      return;
    const annotations = this.store.peek(path);
    if (annotations.length === 0)
      return;
    const next = /* @__PURE__ */ new Map();
    for (const a of annotations) {
      if (a.anchor.kind !== "markdown")
        continue;
      const at = mapRange(a.anchor.from, a.anchor.to, changes);
      if (!at)
        continue;
      const updated = reanchor(a.anchor, text, at);
      if (anchorsDiffer(a.anchor, updated))
        next.set(a.id, updated);
    }
    if (next.size > 0)
      this.schedule(path, next);
  }
  /**
   * A render found an anchor somewhere other than where it was stored.
   *
   * Writing that back means the next read takes the exact-offset path instead
   * of searching the document again, every time, forever.
   */
  noteResolved(path, id, anchor, text, at) {
    const updated = reanchor(anchor, text, at);
    if (anchorsDiffer(anchor, updated))
      this.schedule(path, /* @__PURE__ */ new Map([[id, updated]]));
  }
  schedule(path, updates) {
    const existing = this.pending.get(path);
    if (existing)
      clearTimeout(existing);
    this.pending.set(path, setTimeout(() => {
      this.pending.delete(path);
      void this.flush(path, updates);
    }, SETTLE_MS));
  }
  async flush(path, updates) {
    for (const [id, anchor] of updates) {
      await this.store.update(path, id, { anchor });
    }
  }
  dispose() {
    for (const t of this.pending.values())
      clearTimeout(t);
    this.pending.clear();
  }
};

// src/hosts/markdown/readingMode.ts
var import_obsidian10 = require("obsidian");
function repaintReadingViews(app, provider) {
  for (const leaf of app.workspace.getLeavesOfType("markdown")) {
    const view = leaf.view;
    if (!(view instanceof import_obsidian10.MarkdownView) || !view.file)
      continue;
    const container = view.contentEl.querySelector(".markdown-preview-view");
    if (!(container instanceof HTMLElement))
      continue;
    const annotations = provider(view.file.path);
    if (annotations.length === 0)
      continue;
    paintImages(container, annotations);
    for (const a of annotations) {
      if (a.anchor.kind !== "markdown")
        continue;
      paintQuote(container, a, strip(a.anchor.quote));
    }
  }
}
function readingModeHighlighter(provider) {
  return (el, ctx) => {
    const annotations = provider(ctx.sourcePath);
    if (annotations.length === 0)
      return;
    paintImages(el, annotations);
    for (const a of annotations) {
      if (a.anchor.kind !== "markdown")
        continue;
      paintQuote(el, a, strip(a.anchor.quote));
    }
  };
}

// src/hosts/transcript/TranscriptHost.ts
var import_obsidian11 = require("obsidian");

// src/anchor/transcriptAnchor.ts
var TIME_TOLERANCE_S = 3;
function describeTranscript(seg, charStart, charEnd, track, contextLen = 32) {
  return {
    kind: "transcript",
    track,
    seg: seg.seg,
    start: seg.start,
    charStart,
    charEnd,
    quote: seg.text.slice(charStart, charEnd),
    prefix: seg.text.slice(Math.max(0, charStart - contextLen), charStart),
    suffix: seg.text.slice(charEnd, charEnd + contextLen)
  };
}
function commonSuffixLen2(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[a.length - 1 - n] === b[b.length - 1 - n])
    n++;
  return n;
}
function commonPrefixLen2(a, b) {
  let n = 0;
  while (n < a.length && n < b.length && a[n] === b[n])
    n++;
  return n;
}
function resolveTranscript(segs, anchor, currentTrack) {
  if (!anchor.quote)
    return null;
  const sameTrack = currentTrack != null && currentTrack === anchor.track;
  if (sameTrack) {
    const seg = segs.find((s) => s.seg === anchor.seg);
    if (seg) {
      if (seg.text.slice(anchor.charStart, anchor.charEnd) === anchor.quote) {
        return { seg: seg.seg, charStart: anchor.charStart, charEnd: anchor.charEnd, how: "exact" };
      }
      const at = seg.text.indexOf(anchor.quote);
      if (at >= 0) {
        return { seg: seg.seg, charStart: at, charEnd: at + anchor.quote.length, how: "drifted" };
      }
    }
  }
  const near = segs.filter((s) => Math.abs(s.start - anchor.start) <= TIME_TOLERANCE_S);
  const scored = [];
  for (const s of near) {
    const at = s.text.indexOf(anchor.quote);
    if (at < 0)
      continue;
    scored.push({
      seg: s,
      at,
      score: commonSuffixLen2(s.text.slice(0, at), anchor.prefix) + commonPrefixLen2(s.text.slice(at + anchor.quote.length), anchor.suffix)
    });
  }
  if (scored.length > 0) {
    scored.sort((a, b) => b.score - a.score || Math.abs(a.seg.start - anchor.start) - Math.abs(b.seg.start - anchor.start));
    const best = scored[0];
    return {
      seg: best.seg.seg,
      charStart: best.at,
      charEnd: best.at + anchor.quote.length,
      how: "retimed"
    };
  }
  const everywhere = segs.filter((s) => s.text.includes(anchor.quote));
  if (everywhere.length === 1) {
    const s = everywhere[0];
    const at = s.text.indexOf(anchor.quote);
    return { seg: s.seg, charStart: at, charEnd: at + anchor.quote.length, how: "unique" };
  }
  return null;
}

// src/hosts/transcript/TranscriptHost.ts
var TRANSCRIPT_RENDERED = "mt:transcript-rendered";
var TranscriptHost = class {
  constructor(app, plugin, store, settings) {
    this.app = app;
    this.plugin = plugin;
    this.store = store;
    this.settings = settings;
    this.popover = new SelectionPopover();
    this.bubble = new CommentBubble(settings.timeFormat);
  }
  register() {
    const onRendered = (e) => {
      var _a;
      const detail = e.detail;
      if (!(detail == null ? void 0 : detail.mediaPath))
        return;
      const panel = e.target instanceof HTMLElement ? (_a = e.target.querySelector(".mt-transcript")) != null ? _a : e.target : null;
      if (panel instanceof HTMLElement)
        void this.repaint(panel);
    };
    document.addEventListener(TRANSCRIPT_RENDERED, onRendered);
    this.plugin.register(() => document.removeEventListener(TRANSCRIPT_RENDERED, onRendered));
    this.plugin.register(this.store.onChange((path) => this.repaintOpenPanels(path)));
    this.plugin.registerDomEvent(document, "mouseup", (e) => {
      if (e.button !== 0 || !this.settings.popoverOnSelection)
        return;
      if (!this.inTranscript(e.target))
        return;
      if (e.target instanceof HTMLElement && e.target.closest(".at-hl, .at-popover, .at-bubble"))
        return;
      window.setTimeout(() => {
        void this.onSelectionMade();
      }, 0);
    });
    this.plugin.registerDomEvent(document, "click", (e) => {
      var _a, _b;
      const hit = e.target instanceof HTMLElement ? e.target.closest(".at-hl") : null;
      if (!(hit instanceof HTMLElement) || !this.inTranscript(hit))
        return;
      if (((_b = (_a = window.getSelection()) == null ? void 0 : _a.toString().trim().length) != null ? _b : 0) > 0)
        return;
      void this.showBubble(hit);
    });
    const onContextMenu = (e) => {
      var _a, _b;
      if (!this.inTranscript(e.target))
        return;
      const hit = e.target instanceof HTMLElement ? e.target.closest(".at-hl") : null;
      const selected = (_b = (_a = window.getSelection()) == null ? void 0 : _a.toString().trim()) != null ? _b : "";
      if (!hit && selected.length === 0)
        return;
      e.preventDefault();
      e.stopPropagation();
      void this.showMenu(e, hit instanceof HTMLElement ? hit : null);
    };
    document.addEventListener("contextmenu", onContextMenu, true);
    this.plugin.register(() => document.removeEventListener("contextmenu", onContextMenu, true));
  }
  detach() {
    this.popover.hide();
    this.bubble.hide();
  }
  inTranscript(target) {
    return this.panelOf(target) != null;
  }
  /**
   * The transcript panel containing `target`, and what it is showing.
   *
   * Read from the DOM rather than remembered from the announcement: a plugin
   * enabled while a transcript is already open never sees that event, and state
   * kept only in a handler is state you can miss.
   */
  panelOf(target) {
    var _a, _b;
    if (!(target instanceof HTMLElement))
      return null;
    const panel = target.closest(".mt-transcript");
    if (!(panel instanceof HTMLElement))
      return null;
    const mediaPath = (_a = panel.dataset.mtMedia) != null ? _a : "";
    if (!mediaPath)
      return null;
    return { panel, mediaPath, trackPath: (_b = panel.dataset.mtTrack) != null ? _b : "" };
  }
  // ── Painting ───────────────────────────────────────────────────────────────
  /** Read the transcript out of the DOM the other plugin rendered. */
  readSegments(panel) {
    const out = [];
    for (const el of Array.from(panel.querySelectorAll(".mt-segment"))) {
      if (!(el instanceof HTMLElement))
        continue;
      const txt = el.querySelector(".mt-txt");
      const seg = Number(el.dataset.mtSeg);
      const start = Number(el.dataset.mtStart);
      if (!(txt instanceof HTMLElement) || !Number.isFinite(seg))
        continue;
      out.push({ el, txt, seg: { seg, start, text: txt.innerText } });
    }
    return out;
  }
  async repaint(panel) {
    var _a;
    const mediaPath = panel.dataset.mtMedia;
    if (!mediaPath)
      return;
    const lines = this.readSegments(panel);
    if (lines.length === 0)
      return;
    const data = await this.store.get(mediaPath);
    const segs = lines.map((l) => l.seg);
    const track = (_a = panel.dataset.mtTrack) != null ? _a : null;
    for (const a of data.annotations) {
      if (a.anchor.kind !== "transcript")
        continue;
      const hit = resolveTranscript(segs, a.anchor, track);
      if (!hit)
        continue;
      const line = lines.find((l) => l.seg.seg === hit.seg);
      if (line)
        paintQuote(line.txt, a, line.seg.text.slice(hit.charStart, hit.charEnd));
    }
  }
  repaintOpenPanels(mediaPath) {
    for (const panel of Array.from(document.querySelectorAll(".mt-transcript"))) {
      if (panel instanceof HTMLElement && panel.dataset.mtMedia === mediaPath) {
        void this.repaint(panel);
      }
    }
  }
  // ── Capture ────────────────────────────────────────────────────────────────
  /** Turn the current selection into an anchor, if it sits inside one line. */
  capture() {
    var _a, _b;
    const selection = window.getSelection();
    const selected = (_a = selection == null ? void 0 : selection.toString()) != null ? _a : "";
    if (!selection || selected.trim().length === 0)
      return null;
    const node = selection.anchorNode;
    const el = (_b = node instanceof HTMLElement ? node : node == null ? void 0 : node.parentElement) != null ? _b : null;
    const where = this.panelOf(el);
    if (!where)
      return null;
    const segEl = el == null ? void 0 : el.closest(".mt-segment");
    const txt = segEl == null ? void 0 : segEl.querySelector(".mt-txt");
    if (!(segEl instanceof HTMLElement) || !(txt instanceof HTMLElement))
      return null;
    const text = txt.innerText;
    const at = text.indexOf(selected);
    if (at < 0) {
      new import_obsidian11.Notice("Attention: select within a single transcript line.");
      return null;
    }
    const seg = {
      seg: Number(segEl.dataset.mtSeg),
      start: Number(segEl.dataset.mtStart),
      text
    };
    return {
      anchor: describeTranscript(seg, at, at + selected.length, where.trackPath),
      mediaPath: where.mediaPath
    };
  }
  async onSelectionMade() {
    const captured = this.capture();
    if (!captured)
      return;
    const selection = window.getSelection();
    if (!selection || selection.rangeCount === 0)
      return;
    this.popover.showAt(selection.getRangeAt(0).getBoundingClientRect(), {
      onMark: () => {
        void this.mark(captured.mediaPath, captured.anchor, null);
      },
      onComment: () => {
        new CommentModal(this.app, captured.anchor.quote, "", (body) => {
          void this.mark(captured.mediaPath, captured.anchor, body || null);
        }).open();
      }
    });
  }
  async showMenu(e, hit) {
    var _a;
    const menu = new import_obsidian11.Menu();
    if (hit) {
      const mediaPath = (_a = this.panelOf(hit)) == null ? void 0 : _a.mediaPath;
      const id = hit.dataset.atId;
      if (!mediaPath || !id)
        return;
      menu.addItem((i) => i.setTitle("Edit comment\u2026").setIcon("message-square").onClick(() => {
        void this.editComment(mediaPath, id);
      }));
      menu.addItem((i) => i.setTitle("Remove mark").setIcon("trash").setWarning(true).onClick(() => {
        void this.store.remove(mediaPath, id);
      }));
    } else {
      const captured = this.capture();
      if (!captured)
        return;
      menu.addItem((i) => i.setTitle("Mark").setIcon("highlighter").onClick(() => {
        void this.mark(captured.mediaPath, captured.anchor, null);
      }));
      menu.addItem((i) => i.setTitle("Comment\u2026").setIcon("message-square").onClick(() => {
        new CommentModal(this.app, captured.anchor.quote, "", (body) => {
          void this.mark(captured.mediaPath, captured.anchor, body || null);
        }).open();
      }));
    }
    menu.showAtMouseEvent(e);
  }
  // ── Actions ────────────────────────────────────────────────────────────────
  async showBubble(el) {
    var _a;
    const mediaPath = (_a = this.panelOf(el)) == null ? void 0 : _a.mediaPath;
    const id = el.dataset.atId;
    if (!mediaPath || !id)
      return;
    const data = await this.store.get(mediaPath);
    const annotation = data.annotations.find((a) => a.id === id);
    if (!annotation)
      return;
    this.bubble.showFor(el.getBoundingClientRect(), annotation, {
      onEdit: () => {
        void this.editComment(mediaPath, id);
      },
      onMarkAgain: () => {
        void this.markAgain(mediaPath, id);
      },
      onRemove: () => {
        void this.store.remove(mediaPath, id);
      }
    });
  }
  async markAgain(targetPath, id) {
    const updated = await this.store.markAgain(targetPath, id);
    if (updated)
      new import_obsidian11.Notice(`Marked ${updated.hits.length}\xD7 now`);
  }
  async editComment(mediaPath, id) {
    var _a;
    const data = await this.store.get(mediaPath);
    const annotation = data.annotations.find((a) => a.id === id);
    if (!annotation)
      return;
    new CommentModal(this.app, annotation.anchor.quote, (_a = annotation.body) != null ? _a : "", (body) => {
      void this.store.update(mediaPath, id, { body: body || null });
    }).open();
  }
  async mark(mediaPath, anchor, body) {
    const { repeat, annotation } = await this.store.mark(mediaPath, anchor, body);
    if (repeat)
      new import_obsidian11.Notice(`Marked ${annotation.hits.length}\xD7 now`);
  }
};

// src/main.ts
var AttentionPlugin = class extends import_obsidian12.Plugin {
  constructor() {
    super(...arguments);
    this.markdownHost = null;
    this.transcriptHost = null;
    this.tracker = null;
    /**
     * Show the panel. `focus: false` is used when opening it on the user's behalf
     * — revealing a sidebar is helpful, stealing the cursor mid-sentence is not.
     */
    this.opening = null;
  }
  async onload() {
    await this.loadSettings();
    this.index = new AttentionIndex(this.app);
    this.store = new AnnotationStore(this.app, this.index);
    this.registerView(VIEW_TYPE_REVIEW, (leaf) => new ReviewView(leaf, this));
    this.applyMarkStyle();
    this.applyMarkColor();
    if (this.settings.enableMarkdownHost)
      this.setupMarkdownHost();
    if (this.settings.enableTranscriptHost) {
      this.transcriptHost = new TranscriptHost(this.app, this, this.store, this.settings);
      this.transcriptHost.register();
    }
    this.register(this.store.onChange(() => {
      repaintEditors(this.app, (path) => this.store.peek(path));
      this.rerenderReadingViews();
      this.refreshReviewViews();
    }));
    this.registerEvent(this.app.workspace.on("file-open", (file) => {
      if (file)
        void this.onFileOpen(file);
    }));
    this.app.workspace.onLayoutReady(() => {
      void this.onLayoutReady();
    });
    this.addRibbonIcon("highlighter", "Attention", () => {
      void this.openReview();
    });
    this.addCommand({
      id: "open-review",
      name: "Open attention review",
      callback: () => {
        void this.openReview();
      }
    });
    this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
      void this.handleRename(file, oldPath);
    }));
    this.registerEvent(this.app.vault.on("delete", (file) => {
      void this.handleDelete(file);
    }));
    this.addSettingTab(new AttentionSettingTab(this.app, this));
  }
  /** Mark style is a body class, so switching it needs no repaint. */
  applyMarkStyle() {
    document.body.toggleClass("at-style-background", this.settings.markStyle === "background");
  }
  /** One colour for every mark, published as a variable so nothing repaints. */
  applyMarkColor() {
    document.body.style.setProperty("--at-color", this.settings.markColor);
  }
  /**
   * Opening a sidecar opens what it annotates instead.
   *
   * `<note>.anno.json` is plumbing — nobody clicks it wanting to read JSON, and
   * `.json` is claimed by whichever plugin registered the extension, which then
   * has to explain a file it knows nothing about. Redirecting keeps that
   * knowledge here, where the naming convention lives.
   */
  async redirectSidecar(file) {
    if (!isSidecarPath(file.path))
      return false;
    const targetPath = targetPathFor(file.path);
    const target = targetPath && this.app.vault.getAbstractFileByPath(targetPath);
    if (!(target instanceof import_obsidian12.TFile)) {
      new import_obsidian12.Notice(
        `Attention: \u201C${targetPath != null ? targetPath : file.name}\u201D no longer exists. Its marks are still here \u2014 delete this file to discard them.`
      );
      return false;
    }
    this.replaceOpenFile(file.path, target);
    return true;
  }
  /**
   * Swap what a leaf is showing, once Obsidian has finished putting it there.
   *
   * This runs from inside `file-open`, and Obsidian completes its own open
   * *after* the handler returns — an openFile issued here is quietly undone a
   * moment later, which looks exactly like the redirect never firing. Deferring
   * by a fixed delay works but bets on a number; retrying until the leaf
   * actually moved is the same idea without the guess, and stops on its own if
   * the reader navigates somewhere else first.
   */
  replaceOpenFile(from, target) {
    let attempts = 0;
    const attempt = () => {
      var _a;
      if (((_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) !== from)
        return;
      void this.app.workspace.getLeaf(false).openFile(target);
      if (++attempts < 8)
        window.setTimeout(attempt, 40);
    };
    window.setTimeout(attempt, 0);
  }
  async onLayoutReady() {
    await this.rebuildIndex();
    await this.warmOpenFiles();
  }
  async warmOpenFiles() {
    const paths = /* @__PURE__ */ new Set();
    this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
      const file = leaf.view instanceof import_obsidian12.MarkdownView ? leaf.view.file : null;
      if (file)
        paths.add(file.path);
    });
    await Promise.all([...paths].map((p) => this.store.warm(p)));
  }
  async onFileOpen(file) {
    if (await this.redirectSidecar(file))
      return;
    await this.store.warm(file.path);
    if (!this.settings.autoRevealPanel)
      return;
    if (this.store.peek(file.path).length === 0)
      return;
    await this.openReview({ focus: false });
  }
  setupMarkdownHost() {
    const provider = (path) => this.store.peek(path);
    this.tracker = new AnchorTracker(this.store);
    setEditListener((path, changes, text) => {
      var _a;
      return (_a = this.tracker) == null ? void 0 : _a.onEdit(path, changes, text);
    });
    setDriftListener((path, id, anchor, text, at) => {
      var _a;
      return (_a = this.tracker) == null ? void 0 : _a.noteResolved(path, id, anchor, text, at);
    });
    this.register(() => {
      setEditListener(null);
      setDriftListener(null);
    });
    this.registerEditorExtension(annotationDecorations(provider));
    this.registerMarkdownPostProcessor(readingModeHighlighter(provider));
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      repaintReadingViews(this.app, provider);
    }));
    this.markdownHost = new MarkdownHost(this.app, this, this.store, this.settings);
    this.markdownHost.register();
  }
  /** Reading mode caches its HTML, so post-processors only re-run on request. */
  rerenderReadingViews() {
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const view = leaf.view;
      if (view instanceof import_obsidian12.MarkdownView && view.getMode() === "preview") {
        view.previewMode.rerender(true);
      }
    }
  }
  /** Redraw after a setting that only affects how things are shown. */
  refreshPanels() {
    this.refreshReviewViews();
  }
  async rebuildIndex() {
    await this.index.rebuild();
    this.refreshReviewViews();
  }
  /** Record that an annotation resurfaced, so future picks can prefer others. */
  async markReviewed(entry) {
    const data = await loadSidecar(this.app, entry.targetPath);
    const target = data.annotations.find((a) => a.id === entry.annotation.id);
    if (!target)
      return;
    target.reviewed.push(new Date().toISOString());
    await saveSidecar(this.app, data);
    this.index.replaceFile(entry.targetPath, data.annotations);
  }
  async openReview(opts = {}) {
    var _a;
    this.opening = ((_a = this.opening) != null ? _a : Promise.resolve()).then(() => this.doOpenReview(opts));
    return this.opening;
  }
  async doOpenReview({ focus = true } = {}) {
    var _a;
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_REVIEW);
    const leaf = (_a = existing[0]) != null ? _a : this.app.workspace.getRightLeaf(false);
    if (!leaf)
      return;
    if (!(leaf.view instanceof ReviewView)) {
      await leaf.setViewState({ type: VIEW_TYPE_REVIEW, active: focus });
    }
    await leaf.loadIfDeferred();
    await this.app.workspace.revealLeaf(leaf);
    if (!focus) {
      const editor = this.app.workspace.getActiveViewOfType(import_obsidian12.MarkdownView);
      if (editor)
        this.app.workspace.setActiveLeaf(editor.leaf, { focus: true });
    }
  }
  refreshReviewViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_REVIEW)) {
      if (leaf.isDeferred)
        continue;
      if (!leaf.view.containerEl.isConnected)
        continue;
      if (leaf.view instanceof ReviewView)
        void leaf.view.render();
    }
  }
  /**
   * Keep the sidecar beside its target. Folder moves need no work — the sidecar
   * is a sibling, so it travels with the folder — only a file's own rename does.
   */
  async handleRename(file, oldPath) {
    if (!(file instanceof import_obsidian12.TFile) || isSidecarPath(file.path))
      return;
    const old = this.app.vault.getAbstractFileByPath(sidecarPathFor(oldPath));
    if (!(old instanceof import_obsidian12.TFile))
      return;
    const nextPath = sidecarPathFor(file.path);
    if (old.path === nextPath)
      return;
    try {
      await this.app.fileManager.renameFile(old, nextPath);
      const data = await loadSidecar(this.app, file.path);
      await saveSidecar(this.app, data);
      this.store.forget(oldPath);
      this.index.renameFile(oldPath, file.path);
      this.refreshReviewViews();
    } catch (e) {
      new import_obsidian12.Notice(`Attention: could not move annotations for ${file.name}`);
      console.error(e);
    }
  }
  async handleDelete(file) {
    if (!(file instanceof import_obsidian12.TFile) || isSidecarPath(file.path))
      return;
    if (this.settings.keepOrphanedSidecars)
      return;
    const sidecar = this.app.vault.getAbstractFileByPath(sidecarPathFor(file.path));
    if (sidecar instanceof import_obsidian12.TFile)
      await this.app.fileManager.trashFile(sidecar);
    this.store.forget(file.path);
    this.index.replaceFile(file.path, []);
    this.refreshReviewViews();
  }
  onunload() {
    var _a, _b, _c;
    (_a = this.markdownHost) == null ? void 0 : _a.detach();
    (_b = this.tracker) == null ? void 0 : _b.dispose();
    (_c = this.transcriptHost) == null ? void 0 : _c.detach();
    document.body.removeClass("at-style-background");
    document.body.style.removeProperty("--at-color");
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved != null ? saved : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
